package modulekinds

import (
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/connectors"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/ad_audit"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aix"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/apache"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/apache2"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/as_400"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/auditd"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_beanstalk"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_cloudtrail"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_fargate"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_iam_user"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_lambda"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_postgresql"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_sql_server"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/aws_traffic_mirror"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/azure"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/bitdefender"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/cisco"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/cisco_switch"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/crowdstrike"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/deceptive_bytes"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/elasticsearch"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/eset"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/file_integrity"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/fire_power"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/fortigate"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/fortiweb"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/gcp"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/github"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/haproxy"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/iis"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/json_logs"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/kafka"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/kaspersky"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/kibana"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/linux_agent"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/linux_logs"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/logstash"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/macos"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/macos_agent"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/meraki"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/mikrotik"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/mongodb"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/mysql"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/nats"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/netflow"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/nginx"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/o365"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/oracle"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/osquery"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/palo_alto"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/pfsense"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/postgresql"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/redis"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/salesforce"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/sentinel_one"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/soc_ai"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/sonic_wall"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/sophos"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/sophos_xg"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/suricata"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/syslog"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/syslog_generic"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/traefik"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/ufw"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/utmstack"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/vmware"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/windows_agent"
	"github.com/utmstack/utmstack/backend/modules/modulesconfig/modulekinds/windows_events"
)

// RegisterAll wires every per-kind package into the factory. The order mirrors
// the legacy ModuleName enum (alphabetised within each group) so a diff
// against the Java side is straightforward. Adding a new kind: drop a package
// under modulekinds/<kind>/ and add one line below.
func RegisterAll(factory connectors.ModuleFactory) {
	factory.Register(ad_audit.New())
	factory.Register(aix.New())
	factory.Register(apache.New())
	factory.Register(apache2.New())
	factory.Register(as_400.New())
	factory.Register(auditd.New())
	factory.Register(aws_beanstalk.New())
	factory.Register(aws_cloudtrail.New())
	factory.Register(aws_fargate.New())
	factory.Register(aws_iam_user.New())
	factory.Register(aws_lambda.New())
	factory.Register(aws_postgresql.New())
	factory.Register(aws_sql_server.New())
	factory.Register(aws_traffic_mirror.New())
	factory.Register(azure.New())
	factory.Register(bitdefender.New())
	factory.Register(cisco.New())
	factory.Register(cisco_switch.New())
	factory.Register(crowdstrike.New())
	factory.Register(deceptive_bytes.New())
	factory.Register(elasticsearch.New())
	factory.Register(eset.New())
	factory.Register(file_integrity.New())
	factory.Register(fire_power.New())
	factory.Register(fortigate.New())
	factory.Register(fortiweb.New())
	factory.Register(gcp.New())
	factory.Register(github.New())
	factory.Register(haproxy.New())
	factory.Register(iis.New())
	factory.Register(json_logs.New())
	factory.Register(kafka.New())
	factory.Register(kaspersky.New())
	factory.Register(kibana.New())
	factory.Register(linux_agent.New())
	factory.Register(linux_logs.New())
	factory.Register(logstash.New())
	factory.Register(macos.New())
	factory.Register(macos_agent.New())
	factory.Register(meraki.New())
	factory.Register(mikrotik.New())
	factory.Register(mongodb.New())
	factory.Register(mysql.New())
	factory.Register(nats.New())
	factory.Register(netflow.New())
	factory.Register(nginx.New())
	factory.Register(o365.New())
	factory.Register(oracle.New())
	factory.Register(osquery.New())
	factory.Register(palo_alto.New())
	factory.Register(pfsense.New())
	factory.Register(postgresql.New())
	factory.Register(redis.New())
	factory.Register(salesforce.New())
	factory.Register(sentinel_one.New())
	factory.Register(soc_ai.New())
	factory.Register(sonic_wall.New())
	factory.Register(sophos.New())
	factory.Register(sophos_xg.New())
	factory.Register(suricata.New())
	factory.Register(syslog.New())
	factory.Register(syslog_generic.New())
	factory.Register(traefik.New())
	factory.Register(ufw.New())
	factory.Register(utmstack.New())
	factory.Register(vmware.New())
	factory.Register(windows_agent.New())
	factory.Register(windows_events.New())
}
