# Netflow firewall module filter, version 3.0.0
# Based in docs and Netflow Generator (Solarwinds) for send log
# 
# Documentations
# 1- https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html 
# 2- http://www.iana.org/assignments/ipfix/ipfix.xhtml 
# 3- https://helpdesk.kaseya.com/hc/en-gb/articles/115003522631-How-to-view-NetFlow-in-WireShark 
# 4- https://www.solarwinds.com/free-tools/
# 
# Implementation
# 1. Parsing the RAW field containing the Netflow
pipeline:
  - dataTypes:
      - netflow
    steps:

      # Using the kv filter with default config, usefull in key-value logs
      - kv:
          fieldSplit: " "
          valueSplit: "="

      # Remove fields that have issues with kv filter
      - delete:
          fields:
            - log.msg
      
      # Using grok to parse kv issued fields
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: '{{.data}}(msg=)'
            - fieldName: log.msg
              pattern: '{{.data}}({{.word}}=)'
            - fieldName: log.irrelevant
              pattern: '{{.greedy}}'
          source: log.kvMessage

      # Using grok to remove irrelevant data
      - grok:
          patterns:
            - fieldName: log.msg
              pattern: '{{.greedy}}{{.space}}'
            - fieldName: log.irrelevant
              pattern: '{{.word}}(=)'
          source: log.msg

      # Rename filds
      - rename:
          from:
            - log.srcIp
          to: origin.ip
      - rename:
          from:
            - log.dstIp
          to: target.ip
      - rename:
          from:
            - log.src_ip
          to: origin.ip
      - rename:
          from:
            - log.dest_ip
          to: target.ip
      - rename:
          from:
            - log.proto
          to: protocol
      - rename:
          from:
            - log.srcPort
          to: origin.port
      - rename:
          from:
            - log.src_port
          to: origin.port
      - rename:
          from:
            - log.dstPort
          to: taget.port
      - rename:
          from:
            - log.dest_port
          to: target.port

      # Fields conversions
      - cast:
          to: 'int'
          fields:
            - origin.port
            - target.port

      # Adding geolocation to origin.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: origin.ip
            destination: origin.geolocation
          where:
            variables:
              - get: origin.ip
                as: ip
                ofType: string
            expression: "ip_ok == true"
      
      # Adding geolocation to target.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: target.ip
            destination: target.geolocation
          where:
            variables:
              - get: target.ip
                as: ip
                ofType: string
            expression: "ip_ok == true"