# Sophos_GX filter using "SF syslog file guide 20.0"
# Supports
# log_type="Content Filtering" log_component="HTTP" log_subtype="Allowed".
# log_type="Content Filtering" log_component="Application" log_subtype="Denied"
# log_type="Anti-Virus" log_component="HTTPS|FTP" log_subtype="Virus"

# See: https://docs.sophos.com/nsg/sophos-firewall/20.0/pdf/sf-syslog-guide-20.0.pdf
# and https://docs.sophos.com/nsg/sophos-firewall/20.0/Help/en-us/webhelp/onlinehelp/AdministratorHelp/Logs/TroubleshootingLogs/LogFileDetails/index.html#https-ftp-waf


pipeline:
  - dataTypes:
      - firewall-sophos-xg
    steps:
      # Parsing the raw field for log_type="Content Filtering" log_component="HTTP" log_subtype="Allowed"
      - grok:
          patterns:
            - fieldName: log.1trash
              pattern: '\<{{.data}}\>'
            - fieldName: log.2blockToParse
              pattern: '{{.data}}device_name=\"{{.data}}\"'
            - fieldName: log.3blockToParse
              pattern: '{{.data}}log_component=\"{{.data}}\"'
            - fieldName: log.4blockToParse
              pattern: '{{.data}}user_agent=\"{{.data}}\"'
            - fieldName: log.5blockToParse
              pattern: '{{.data}}download_file_name=\"{{.data}}\"'
            - fieldName: log.6blockToParse
              pattern: '{{.data}}upload_file_name=\"{{.data}}\"'
            - fieldName: log.1blockToParse
              pattern: '{{.greedy}}'
          source: raw

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.1blockToParse

      # Parsing the 2block field
      - grok:
          patterns:
            - fieldName: log.2trash
              pattern: '{{.word}}\='
            - fieldName: log.deviceType
              pattern: '\"{{.data}}\"'
            - fieldName: log.7blockToParse
              pattern: '{{.data}}timezone=\"{{.data}}\"'
            - fieldName: log.3trash
              pattern: '{{.word}}\='
            - fieldName: log.devicename
              pattern: '\"{{.data}}\"'
          source: log.2blockToParse

      # Parsing the 3block field
      - grok:
          patterns:
            - fieldName: log.4trash
              pattern: '{{.word}}\='
            - fieldName: log.deviceId
              pattern: '{{.word}}\s'
            - fieldName: log.5trash
              pattern: '{{.data}}\='
            - fieldName: log.logid
              pattern: '{{.word}}\s'
            - fieldName: log.6trash
              pattern: '{{.data}}\='
            - fieldName: log.logtype
              pattern: '\"{{.data}}\"'
            - fieldName: log.7trash
              pattern: '{{.data}}\='
            - fieldName: log.logcomponent
              pattern: '\"{{.data}}\"'
          source: log.3blockToParse

      # Parsing the 4block field
      - grok:
          patterns:
            - fieldName: log.8blockToParse
              pattern: '{{.data}}user_agent='
            - fieldName: log.userAgent
              pattern: '\"{{.data}}\"'
          source: log.4blockToParse

      # Parsing the 5block field
      - grok:
          patterns:
            - fieldName: log.9blockToParse
              pattern: '{{.data}}referer='
            - fieldName: log.referer
              pattern: '\"{{.data}}\"'
            - fieldName: log.9trash
              pattern: '{{.data}}\='
            - fieldName: log.downloadFileName
              pattern: '\"{{.data}}\"'
          source: log.5blockToParse

      - grok:
          patterns:
            - fieldName: log.2blockToKv
              pattern: '{{.data}}transactionid={{.data}}'
            - fieldName: log.10trash
              pattern: 'referer='
          source: log.9blockToParse

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.2blockToKv
      
      # Parsing the 6block field
      - grok:
          patterns:
            - fieldName: log.11trash
              pattern: '{{.data}}\='
            - fieldName: log.downloadFileType
              pattern: '\"{{.data}}\"'
            - fieldName: log.12trash
              pattern: '{{.data}}\='
            - fieldName: log.uploadFileName
              pattern: '\"{{.data}}\"'
          source: log.6blockToParse

      # Parsing the 7block field
      - grok:
          patterns:
            - fieldName: log.13trash
              pattern: '{{.data}}\='
            - fieldName: log.date
              pattern: '{{.year}}\-{{.monthNumber}}\-{{.monthDay}}'
            - fieldName: log.14trash
              pattern: '{{.data}}\='
            - fieldName: log.time
              pattern: '{{.time}}'
            - fieldName: log.15trash
              pattern: '{{.data}}\='
            - fieldName: log.timezone
              pattern: '\"{{.data}}\"'
          source: log.7blockToParse

      # Parsing the 8block field
      - grok:
          patterns:
            - fieldName: log.1blockToKv
              pattern: '{{.data}}reason=\"{{.data}}\"'
            - fieldName: log.8trash
              pattern: 'user_agent='
          source: log.8blockToParse

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.1blockToKv
      
      # Parsing the 9block field
      - grok:
          patterns:
            - fieldName: log.16trash
              pattern: '{{.data}}\='
            - fieldName: log.statusCode
              pattern: '\"{{.data}}\"'
            - fieldName: log.17trash
              pattern: '{{.data}}\='
            - fieldName: log.transactionId
              pattern: '{{.data}}'
            - fieldName: log.18trash
              pattern: '{{.greedy}}'
          source: log.9blockToParse

      # Parsing the raw field for log_type="Content Filtering" log_component="Application" log_subtype="Denied"
      - grok:
          patterns:
            - fieldName: log.1trash
              pattern: '\<{{.data}}\>'
            - fieldName: log.2blockToParse
              pattern: '{{.data}}device_name=\"{{.data}}\"'
            - fieldName: log.3blockToParse
              pattern: '{{.data}}log_component=\"{{.data}}\"'
            - fieldName: log.4blockToParse
              pattern: '{{.data}}category=\"{{.data}}\"'
            - fieldName: log.5blockToParse
              pattern: '{{.data}}application_name=\"{{.data}}\"'
            - fieldName: log.6blockToParse
              pattern: '{{.data}}application_technology=\"{{.data}}\"'
            - fieldName: log.7blockToParse
              pattern: '{{.data}}application_category=\"{{.data}}\"'
            - fieldName: log.8blockToParse
              pattern: '{{.data}}message=\"{{.data}}\"'
            - fieldName: log.1blockToParse
              pattern: '{{.greedy}}'
          source: raw

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.1blockToParse

      # Parsing the 2block field
      - grok:
          patterns:
            - fieldName: log.2trash
              pattern: '{{.word}}\='
            - fieldName: log.deviceType
              pattern: '\"{{.data}}\"'
            - fieldName: log.9blockToParse
              pattern: '{{.data}}timezone=\"{{.data}}\"'
            - fieldName: log.3trash
              pattern: '{{.word}}\='
            - fieldName: log.devicename
              pattern: '\"{{.data}}\"'
          source: log.2blockToParse

      # Parsing the 3block field
      - grok:
          patterns:
            - fieldName: log.10blockToParse
              pattern: '{{.data}}log_type='
            - fieldName: log.logtype
              pattern: '\"{{.data}}\"'
            - fieldName: log.4trash
              pattern: '{{.data}}\='
            - fieldName: log.logcomponent
              pattern: '{{.greedy}}'
          source: log.3blockToParse

      # Parsing the 9block field
      - grok:
          patterns:
            - fieldName: log.13trash
              pattern: '{{.data}}\='
            - fieldName: log.date
              pattern: '{{.year}}\-{{.monthNumber}}\-{{.monthDay}}'
            - fieldName: log.14trash
              pattern: '{{.data}}\='
            - fieldName: log.time
              pattern: '{{.time}}'
            - fieldName: log.15trash
              pattern: '{{.data}}\='
            - fieldName: log.timezone
              pattern: '\"{{.data}}\"'
          source: log.9blockToParse

      # Parsing the 4block field
      - grok:
          patterns:
            - fieldName: log.11blockToParse
              pattern: '{{.data}}category='
            - fieldName: log.category
              pattern: '\"{{.data}}\"'
          source: log.4blockToParse

      # Parsing the 5block field
      - grok:
          patterns:
            - fieldName: log.14trash
              pattern: '{{.data}}\='
            - fieldName: log.applicationName
              pattern: '{{.greedy}}'
          source: log.5blockToParse

      # Parsing the 6block field
      - grok:
          patterns:
            - fieldName: log.15trash
              pattern: '{{.data}}\='
            - fieldName: log.applicationRisk
              pattern: '{{.integer}}'
            - fieldName: log.16trash
              pattern: '{{.data}}\='
            - fieldName: log.applicationTech
              pattern: '{{.greedy}}'
          source: log.6blockToParse

      # Parsing the 7block field
      - grok:
          patterns:
            - fieldName: log.17trash
              pattern: '{{.data}}\='
            - fieldName: log.applicationCategory
              pattern: '{{.greedy}}'
          source: log.7blockToParse

      # Parsing the 8block field
      - grok:
          patterns:
            - fieldName: log.4blockToKv
              pattern: '{{.data}}status={{.data}}'
            - fieldName: log.18trash
              pattern: '{{.data}}\='
            - fieldName: log.message
              pattern: '{{.greedy}}'
          source: log.8blockToParse

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.4blockToKv

      # Parsing the 10block field
      - grok:
          patterns:
            - fieldName: log.5trash
              pattern: '{{.data}}\='
            - fieldName: log.deviceId
              pattern: '{{.word}}'
            - fieldName: log.6trash
              pattern: '{{.data}}\='
            - fieldName: log.logid
              pattern: '{{.word}}'
            - fieldName: log.7trash
              pattern: '{{.greedy}}'
          source: log.10blockToParse

      # Parsing the 11block field
      - grok:
          patterns:
            - fieldName: log.3blockToKv
              pattern: '{{.data}}application_filter_policy={{.word}}'
            - fieldName: log.8trash
              pattern: '{{.greedy}}'
          source: log.11blockToParse

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.3blockToKv

      # Parsing the raw field for log_type="Anti-Virus" log_component="HTTPS|FTP" log_subtype="Virus"
      - grok:
          patterns:
            - fieldName: log.1trash
              pattern: '\<{{.data}}\>'
            - fieldName: log.1blockToParse
              pattern: '{{.greedy}}'
          source: raw

      - kv:
          fieldSplit: " "
          valueSplit: "="
          source: log.1blockToParse

      # Renaming useful fields
      - rename:
          from:
            - log.appiscloud
          to: log.appIsCloud

      - rename:
          from:
            - log.category
          to: log.categoryApp

      - rename:
          from:
            - log.categorytype
          to: log.categoryType

      - rename:
          from:
            - log.contenttype
          to: log.contentType

      - rename:
          from:
            - log.conid
          to: log.connectionId

      - rename:
          from:
            - log.deviceId
          to: log.connectionId

      - rename:
          from:
            - log.domain
          to: log.remoteDomain

      - rename:
          from:
            - log.dstip
          to: log.remoteIp

      - rename:
          from:
            - log.dstport
          to: log.remotePort

      - rename:
          from:
            - log.exceptions
          to: log.webExceptions

      - rename:
          from:
            - log.fwruleid
          to: log.firewallRuleId

      - rename:
          from:
            - log.iap
          to: log.webPolicy

      - rename:
          from:
            - log.logcomponent
          to: log.component

      - rename:
          from:
            - log.logid
          to: log.Id

      - rename:
          from:
            - log.logtype
          to: log.type

      - rename:
          from:
            - log.logsubtype
          to: log.subType

      - rename:
          from:
            - log.recvbytes
          to: log.localBytesReceived

      - rename:
          from:
            - log.sentbytes
          to: log.localBytesSent

      - rename:
          from:
            - log.srcip
          to: log.localIp

      - rename:
          from:
            - log.srcport
          to: log.localPort

      - rename:
          from:
            - log.statuscode
          to: log.statusCode

      - rename:
          from:
            - log.usedquota
          to: log.responseTime

      - rename:
          from:
            - log.usergp
          to: log.userGroup

      - rename:
          from:
            - log.username
          to: log.userName

      - rename:
          from:
            - log.srccountrycode
          to: log.srcCountryCode

      - rename:
          from:
            - log.dstcountrycode
          to: log.dstCountryCode

      - rename:
          from:
            - log.appresolvedby
          to: log.appResolvedBy

      - rename:
          from:
            - log.applicationfilterpolicy
          to: log.applicationFilterPolicy

      - rename:
          from:
            - log.device
          to: log.deviceType

      - rename:
          from:
            - log.devicename
          to: log.deviceName

      - rename:
          from:
            - log.domainname
          to: log.domainName

      - rename:
          from:
            - log.timezone
          to: log.timeZone

      - rename:
          from:
            - log.filename
          to: log.fileName

      - rename:
          from:
            - log.filepath
          to: log.filePath

      - rename:
          from:
            - log.ftpcommand
          to: log.ftpCommand

      - rename:
          from:
            - log.dstdomain
          to: log.dstDomain

      # Removing unnecessary characters
      - trim:
          function: prefix
          substring: '"'
          fields:
            - log.categoryApp
            - log.categoryType
            - log.component
            - log.contentType
            - log.deviceName
            - log.domainName
            - log.dstDomain
            - log.deviceType
            - log.ftpCommand
            - log.fileName
            - log.filePath
            - log.FTPdirection
            - log.FTPurl
            - log.downloadFileName
            - log.downloadFileType
            - log.protocol
            - log.reason
            - log.referer
            - log.status
            - log.statusCode
            - log.subType
            - log.type
            - log.uploadFileName
            - log.uploadfiletype
            - log.url
            - log.virus
            - log.userAgent
            - log.userGroup
            - log.userName
            - log.timeZone
            - log.applicationCategory
            - log.applicationName
            - log.applicationTech
            - log.appResolvedBy

      - trim:
          function: suffix
          substring: '"'
          fields:
            - log.categoryApp
            - log.categoryType
            - log.component
            - log.contentType
            - log.deviceName
            - log.domainName
            - log.dstDomain
            - log.deviceType
            - log.ftpCommand
            - log.fileName
            - log.filePath
            - log.FTPdirection
            - log.FTPurl
            - log.downloadFileName
            - log.downloadFileType
            - log.protocol
            - log.reason
            - log.referer
            - log.status
            - log.statusCode
            - log.subType
            - log.type
            - log.uploadFileName
            - log.uploadfiletype
            - log.url
            - log.virus
            - log.userAgent
            - log.userGroup
            - log.userName
            - log.timeZone
            - log.applicationCategory
            - log.applicationName
            - log.applicationTech
            - log.appResolvedBy

      # Field conversions
      - cast:
          fields:
            - log.statusCode
            - log.localBytesReceived
            - log.localBytesSent
            - log.remotePort
          to: int

      # Removing unused fields
      - delete:
          fields:
            - log.1trash
            - log.2trash
            - log.3trash
            - log.4trash
            - log.5trash
            - log.6trash
            - log.7trash
            - log.8trash
            - log.9trash
            - log.10trash
            - log.11trash
            - log.12trash
            - log.13trash
            - log.14trash
            - log.15trash
            - log.16trash
            - log.17trash
            - log.18trash
            - log.1blockToParse
            - log.2blockToParse
            - log.3blockToParse
            - log.4blockToParse
            - log.5blockToParse
            - log.6blockToParse
            - log.7blockToParse
            - log.8blockToParse
            - log.9blockToParse
            - log.10blockToParse
            - log.11blockToParse
            - log.1blockToKv
            - log.2blockToKv
            - log.3blockToKv
            - log.4blockToKv
            - log.activityname
            - log.application
            - log.httpresponsecode
            - log.overrideauthorizer
            - log.overridename
            - log.overridetoken
            - log.transactionid