export enum FileFieldEnum {
  FILE_TIMESTAMP_FIELD = '@timestamp',
  FILE_OBJECT_NAME_FIELD = 'target.path',        // promoted to a typed text+keyword field by the Windows filter (grok-copy, not rename)
  FILE_PROCESS_NAME_FIELD = 'origin.file',       // promoted to a typed text+keyword field by the Windows filter (grok-copy, not rename)
  FILE_HOST_NAME_FIELD = 'origin.host',          // already canonical
  FILE_HOST_ID_FIELD = 'id',
  FILE_ACCESS_LIST_FIELD = 'event.eventDataAccessList',
  FILE_ACCESS_MASK_FIELD = 'event.eventDataAccessMask',
  FILE_HANDLE_ID_FIELD = 'event.eventDataHandleId',
  FILE_OBJECT_SERVER_FIELD = 'event.eventDataObjectServer',
  FILE_OBJECT_TYPE_FIELD = 'event.eventDataObjectType',
  FILE_PROCESS_ID_FIELD = 'event.eventDataProcessId',
  FILE_RESOURCE_ATT_FIELD = 'event.eventDataResourceAttributes',
  FILE_SUBJECT_DOMAIN_NAME_FIELD = 'event.eventDataSubjectDomainName',
  FILE_SUBJECT_LOGON_ID_FIELD = 'event.eventDataSubjectLogonId',
  FILE_SUBJECT_USER_NAME_FIELD = 'event.eventDataSubjectUserName',
  FILE_SUBJECT_USER_ID_FIELD = 'event.eventDataSubjectUserSid',
  FILE_EVENT_ID_FIELD = 'event.eventCode',
  FILE_EVENT_NAME_FIELD = 'event.eventName',
  FILE_HOST_ARCHITECTURE_FIELD = 'event.cpuArchitecture',
  FILE_HOST_OS_NAME_FIELD = 'target.host',       // log.computer never existed (renamed to target.host by the filter); column was already dead
  FILE_MESSAGE_FIELD = 'event.eventName',
  FILE_NEW_SDDL_FIELD = 'event.eventDataNewSd',
  FILE_OLD_SDDL_FIELD = 'event.eventDataOldSd',
  FILE_HOTS_OS_BUILD_FIELD = 'event.host.os.build',
  FILE_HOST_OS_FAMILY_FIELD = 'event.host.os.family',
  FILE_HOST_OS_PLATFORM_FIELD = 'event.host.os.platform',
  FILE_HOST_OS_VERSION_FIELD = 'event.host.os.version',
  FILE_KEYWORD_FIELD = 'event.keywords',
  FILE_OPCODE_FIELD = 'event.opcode',
  FILE_PROVIDER_GUID_FIELD = 'event.providerGuid',
  FILE_SHARE_NAME_FIELD = 'event.eventDataShareName',
  FILE_SHARE_PATH_FIELD = 'event.eventDataShareLocalPath',
}
