export enum FileQueryParamEnum {
  ALL_EVENTS = 'ALL_EVENTS',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
  FILES_DELETED = 'FILES_DELETED',
  FILES_MODIFIED = 'FILES_MODIFIED',
  FILES_CREATED = 'FILES_CREATED',
  FILES_MOVED = 'FILES_MOVED',
  FILES_RENAMED = 'FILES_RENAMED',
  FILES_SHARED = 'FILES_SHARED'
}
