import { useMemo, useState } from 'react'
import {
  AlertTriangle,
  ArrowRight,
  Code2,
  Copy,
  Database,
  ExternalLink,
  Filter as FilterIcon,
  Globe2,
  GripVertical,
  History,
  ListFilter,
  Lock,
  MoreHorizontal,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Regex,
  Search,
  Sparkles,
  Tag as TagIcon,
  Trash2,
  Upload,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { cn } from '@/shared/lib/utils'
import { Button } from '@/shared/components/ui/button'
import { Input } from '@/shared/components/ui/input'

/* ─── Types ────────────────────────────────────────────────────────────── */

type PipelineStatus = 'healthy' | 'degraded' | 'error' | 'paused'
type FilterKind = 'parse' | 'mutate' | 'date' | 'drop' | 'geoip' | 'enrich' | 'code'

interface PipelineFilter {
  id: string
  name: string
  kind: FilterKind
  systemOwner: boolean
  description: string
  preview: string // pseudo-config snippet
  matched24h?: number
}

interface Pipeline {
  id: string
  integrationId: string  // links to the integration logo
  name: string
  description: string
  status: PipelineStatus
  eventsIn24h: number
  eventsOut24h: number
  rate: number
  errors24h: number
  filters: PipelineFilter[]
  lastError?: string
  modifiedAt: string
}

/* ─── Mock data ────────────────────────────────────────────────────────── */

const NOW = new Date('2026-05-01T16:42:00Z').getTime()
const hr = (h: number) => new Date(NOW - h * 3_600_000).toISOString()
const days = (d: number) => new Date(NOW - d * 86_400_000).toISOString()

const LOGO = (slug: string) => `/integrations/${slug}`

const PIPELINES: Pipeline[] = [
  {
    id: 'p-windows',
    integrationId: 'windows.svg',
    name: 'Windows agent',
    description: 'Sysmon, Security, Application, and File Audit events from the UTMStack Windows agent.',
    status: 'healthy',
    eventsIn24h: 142_004,
    eventsOut24h: 138_881,
    rate: 142,
    errors24h: 0,
    modifiedAt: hr(8),
    filters: [
      { id: 'f-1', name: 'Parse Windows Event XML', kind: 'parse', systemOwner: true,
        description: 'Extract event_data fields from Windows Event XML payload.',
        preview: 'xml { source => "winlog.event_data" }', matched24h: 142_004 },
      { id: 'f-2', name: 'Map event codes to ECS', kind: 'mutate', systemOwner: true,
        description: 'Translate Windows event codes (4624, 4625, 4769) to ECS-compliant fields.',
        preview: 'mutate { rename => { "EventID" => "event.code" } }', matched24h: 142_004 },
      { id: 'f-3', name: 'Drop verbose group policy events', kind: 'drop', systemOwner: false,
        description: 'Drop GPO logging events (5145) generated by the system itself.',
        preview: 'if [event.code] == "5145" and [user.name] == "SYSTEM" { drop {} }',
        matched24h: 3_120 },
      { id: 'f-4', name: 'Enrich logon events with asset metadata', kind: 'enrich', systemOwner: true,
        description: 'Look up host in asset inventory and add asset.criticality, asset.owner, asset.tags.',
        preview: 'asset_lookup { source => "host.name" }', matched24h: 142_004 },
      { id: 'f-5', name: 'Set @timestamp from EventTime', kind: 'date', systemOwner: true,
        description: 'Use EventTime as the canonical timestamp for the document.',
        preview: 'date { match => ["EventTime", "ISO8601"] }', matched24h: 142_004 },
    ],
  },
  {
    id: 'p-linux',
    integrationId: 'linux.svg',
    name: 'Linux agent',
    description: 'auditd, journald, syslog, and /var/log files from the UTMStack Linux agent.',
    status: 'healthy',
    eventsIn24h: 312_000,
    eventsOut24h: 308_421,
    rate: 248,
    errors24h: 0,
    modifiedAt: days(7),
    filters: [
      { id: 'f-1', name: 'Parse auditd records', kind: 'parse', systemOwner: true,
        description: 'Multiline grok parsing of auditd record sequences.',
        preview: 'grok { match => { "message" => "%{AUDITD}" } }', matched24h: 88_104 },
      { id: 'f-2', name: 'Parse journald JSON', kind: 'parse', systemOwner: true,
        description: 'JSON-decode systemd journal export format.',
        preview: 'json { source => "message" }', matched24h: 142_004 },
      { id: 'f-3', name: 'Drop sshd debug messages', kind: 'drop', systemOwner: false,
        description: 'Suppress sshd verbose debug output (set on patches that expose them).',
        preview: 'if [program] == "sshd" and [log.level] == "debug" { drop {} }',
        matched24h: 3_579 },
      { id: 'f-4', name: 'Map syslog severity to ECS', kind: 'mutate', systemOwner: true,
        description: 'Translate syslog priority to ECS log.level.',
        preview: 'mutate { rename => { "syslog_severity" => "log.level" } }', matched24h: 142_004 },
    ],
  },
  {
    id: 'p-firewall',
    integrationId: 'pfsense.svg',
    name: 'pfSense firewall',
    description: 'pfSense filterlog and OpenVPN events received via syslog.',
    status: 'healthy',
    eventsIn24h: 1_204_882,
    eventsOut24h: 1_198_412,
    rate: 1208,
    errors24h: 0,
    modifiedAt: days(2),
    filters: [
      { id: 'f-1', name: 'Parse filterlog CSV', kind: 'parse', systemOwner: true,
        description: 'Parse pfSense filterlog comma-separated payload.',
        preview: 'grok { match => { "message" => "%{PFSENSE_FILTERLOG}" } }', matched24h: 1_204_882 },
      { id: 'f-2', name: 'Drop allow records to monitoring subnet', kind: 'drop', systemOwner: false,
        description: 'Suppress noisy permitted traffic from internal monitoring hosts.',
        preview: 'if [action] == "pass" and [source.ip] in [10.99.0.0/24] { drop {} }',
        matched24h: 6_470 },
      { id: 'f-3', name: 'GeoIP lookup on source.ip', kind: 'geoip', systemOwner: true,
        description: 'Add source.geo.* fields (country, city, ASN, ASO) using MaxMind DB.',
        preview: 'geoip { source => "source.ip" }', matched24h: 1_204_882 },
      { id: 'f-4', name: 'Threat intel match on destination.ip', kind: 'enrich', systemOwner: true,
        description: 'Tag the event with threat.indicator.* if destination IP is in any IOC feed.',
        preview: 'threat_intel { lookup => "destination.ip" type => "ipv4" }', matched24h: 1_204_882 },
    ],
  },
  {
    id: 'p-suricata',
    integrationId: 'suricata.png',
    name: 'Suricata IDS',
    description: 'Suricata EVE JSON output: alerts, flows, anomaly, http, dns, tls.',
    status: 'healthy',
    eventsIn24h: 88_201,
    eventsOut24h: 88_201,
    rate: 88,
    errors24h: 0,
    modifiedAt: days(15),
    filters: [
      { id: 'f-1', name: 'Parse EVE JSON', kind: 'parse', systemOwner: true,
        description: 'JSON-decode the Suricata EVE event payload.',
        preview: 'json { source => "message" }', matched24h: 88_201 },
      { id: 'f-2', name: 'Route by event_type', kind: 'mutate', systemOwner: true,
        description: 'Add tags so each event_type goes to the right index pattern.',
        preview: 'mutate { add_tag => ["%{event_type}"] }', matched24h: 88_201 },
      { id: 'f-3', name: 'GeoIP both sides', kind: 'geoip', systemOwner: true,
        description: 'Enrich source and destination IPs with geolocation.',
        preview: 'geoip { source => ["source.ip", "destination.ip"] }', matched24h: 88_201 },
    ],
  },
  {
    id: 'p-aws',
    integrationId: 'aws.svg',
    name: 'AWS CloudTrail / GuardDuty',
    description: 'AWS-pulled events: CloudTrail, GuardDuty findings, VPC flow logs, IAM activity.',
    status: 'healthy',
    eventsIn24h: 481_022,
    eventsOut24h: 478_184,
    rate: 482,
    errors24h: 0,
    modifiedAt: hr(8),
    filters: [
      { id: 'f-1', name: 'Parse CloudTrail JSON', kind: 'parse', systemOwner: true,
        description: 'Decode CloudTrail Records[] envelope.',
        preview: 'json { source => "Records" }', matched24h: 412_004 },
      { id: 'f-2', name: 'Map AWS principal to ECS user', kind: 'mutate', systemOwner: true,
        description: 'Translate userIdentity.* fields into ECS user.* schema.',
        preview: 'mutate { rename => { "userIdentity.userName" => "user.name" } }',
        matched24h: 481_022 },
      { id: 'f-3', name: 'Drop AWS Lambda warmup events', kind: 'drop', systemOwner: false,
        description: 'Drop Lambda Invoke events from internal warmup Lambdas to reduce noise.',
        preview: 'if [eventName] == "Invoke" and [requestParameters.functionName] =~ "warmup" { drop {} }',
        matched24h: 2_838 },
      { id: 'f-4', name: 'Enrich account with friendly name', kind: 'enrich', systemOwner: false,
        description: 'Map AWS account IDs to friendly names from the account catalog.',
        preview: 'translate { field => "[recipientAccountId]" dictionary => "aws_accounts.csv" }',
        matched24h: 481_022 },
    ],
  },
  {
    id: 'p-m365',
    integrationId: 'm365.svg',
    name: 'Microsoft 365',
    description: 'M365 Unified Audit Log: Exchange, SharePoint, Teams, OneDrive, Defender alerts.',
    status: 'degraded',
    eventsIn24h: 218_204,
    eventsOut24h: 214_882,
    rate: 218,
    errors24h: 142,
    modifiedAt: days(21),
    lastError: 'Throttled by Graph API · backoff 30s · 142 events deferred',
    filters: [
      { id: 'f-1', name: 'Parse Office 365 audit JSON', kind: 'parse', systemOwner: true,
        description: 'Decode the Office 365 unified audit log envelope.',
        preview: 'json { source => "message" }', matched24h: 218_204 },
      { id: 'f-2', name: 'Map ECS user fields', kind: 'mutate', systemOwner: true,
        description: 'Translate UserId / UserPrincipalName / ObjectId into ECS user.*',
        preview: 'mutate { rename => { "UserId" => "user.email" } }', matched24h: 218_204 },
      { id: 'f-3', name: 'Drop benign mailbox auto-reply', kind: 'drop', systemOwner: false,
        description: 'Suppress automated out-of-office replies that aren\'t security-relevant.',
        preview: 'if [Operation] == "Send" and [auto_reply] == true { drop {} }', matched24h: 1_280 },
    ],
  },
  {
    id: 'p-azure',
    integrationId: 'azure.svg',
    name: 'Microsoft Azure',
    description: 'Azure AD sign-in logs, Activity logs, Defender for Cloud alerts via Graph API.',
    status: 'healthy',
    eventsIn24h: 124_001,
    eventsOut24h: 122_004,
    rate: 124,
    errors24h: 0,
    modifiedAt: days(14),
    filters: [
      { id: 'f-1', name: 'Parse Azure AD JSON', kind: 'parse', systemOwner: true,
        description: 'Decode Azure AD sign-in log JSON envelope.',
        preview: 'json { source => "message" }', matched24h: 124_001 },
      { id: 'f-2', name: 'Map ConditionalAccess fields', kind: 'mutate', systemOwner: true,
        description: 'Pull conditionalAccessStatus and policy IDs into top-level fields.',
        preview: 'mutate { rename => { "conditionalAccessStatus" => "auth.policy.outcome" } }',
        matched24h: 124_001 },
      { id: 'f-3', name: 'GeoIP source.ip', kind: 'geoip', systemOwner: true,
        description: 'Add source.geo.country, city, ASN to sign-in events.',
        preview: 'geoip { source => "source.ip" }', matched24h: 124_001 },
    ],
  },
  {
    id: 'p-paloalto',
    integrationId: 'paloalto.svg',
    name: 'Palo Alto Networks',
    description: 'PAN-OS firewall log forwarding (Traffic, Threat, URL, Auth).',
    status: 'healthy',
    eventsIn24h: 884_204,
    eventsOut24h: 880_881,
    rate: 882,
    errors24h: 0,
    modifiedAt: days(45),
    filters: [
      { id: 'f-1', name: 'Parse PAN-OS CEF', kind: 'parse', systemOwner: true,
        description: 'Decode PAN-OS Common Event Format payload.',
        preview: 'cef { source => "message" }', matched24h: 884_204 },
      { id: 'f-2', name: 'Tag sub-types', kind: 'mutate', systemOwner: true,
        description: 'Add tag based on Type column (TRAFFIC / THREAT / URL / AUTH).',
        preview: 'mutate { add_tag => ["%{Type}"] }', matched24h: 884_204 },
      { id: 'f-3', name: 'GeoIP both sides', kind: 'geoip', systemOwner: true,
        description: 'Enrich source and destination IPs with geolocation.',
        preview: 'geoip { source => ["src", "dst"] }', matched24h: 884_204 },
    ],
  },
  {
    id: 'p-asa',
    integrationId: 'cisco.svg',
    name: 'Cisco ASA',
    description: 'Cisco ASA firewall syslog with rich message normalization (ACL, VPN, NAT, AAA).',
    status: 'paused',
    eventsIn24h: 0,
    eventsOut24h: 0,
    rate: 0,
    errors24h: 0,
    modifiedAt: days(60),
    filters: [
      { id: 'f-1', name: 'Parse ASA syslog', kind: 'parse', systemOwner: true,
        description: 'Grok pattern set for the most common ASA-110000 series messages.',
        preview: 'grok { match => { "message" => "%{ASA_MESSAGE}" } }' },
      { id: 'f-2', name: 'Map ECS network fields', kind: 'mutate', systemOwner: true,
        description: 'Pull source/destination IP and port into ECS fields.',
        preview: 'mutate { rename => { "src_ip" => "source.ip" } }' },
    ],
  },
  {
    id: 'p-github',
    integrationId: 'github.svg',
    name: 'GitHub',
    description: 'GitHub audit log + Code Scanning alerts via OAuth app or PAT.',
    status: 'error',
    eventsIn24h: 0,
    eventsOut24h: 0,
    rate: 0,
    errors24h: 12,
    modifiedAt: hr(2),
    lastError: '401 Unauthorized · token rotated, please re-authenticate',
    filters: [
      { id: 'f-1', name: 'Parse GitHub audit JSON', kind: 'parse', systemOwner: true,
        description: 'Decode the GitHub audit-log API payload.',
        preview: 'json { source => "message" }' },
      { id: 'f-2', name: 'Map actor to ECS user', kind: 'mutate', systemOwner: true,
        description: 'Translate actor / actor_location.* into ECS user.* and source.geo.*',
        preview: 'mutate { rename => { "actor" => "user.name" } }' },
    ],
  },
]

const FILTER_KIND_META: Record<FilterKind, { label: string; tone: string; icon: LucideIcon }> = {
  parse: { label: 'Parse', tone: 'text-sky-500', icon: Regex },
  mutate: { label: 'Mutate', tone: 'text-violet-500', icon: TagIcon },
  date: { label: 'Date', tone: 'text-amber-500', icon: History },
  drop: { label: 'Drop', tone: 'text-red-500', icon: Trash2 },
  geoip: { label: 'GeoIP', tone: 'text-emerald-500', icon: Globe2 },
  enrich: { label: 'Enrich', tone: 'text-fuchsia-500', icon: Database },
  code: { label: 'Code', tone: 'text-zinc-500', icon: Code2 },
}

const STATUS_META: Record<PipelineStatus, { label: string; dot: string; tone: string }> = {
  healthy: { label: 'Healthy', dot: 'bg-emerald-500', tone: 'text-emerald-500' },
  degraded: { label: 'Degraded', dot: 'bg-amber-500', tone: 'text-amber-500' },
  error: { label: 'Error', dot: 'bg-red-500 animate-pulse', tone: 'text-red-500' },
  paused: { label: 'Paused', dot: 'bg-muted-foreground', tone: 'text-muted-foreground' },
}

/* ─── Saved views ──────────────────────────────────────────────────────── */

interface SavedView {
  id: string
  label: string
  count: number
  predicate: (p: Pipeline) => boolean
}

const SAVED_VIEWS: SavedView[] = [
  { id: 'all', label: 'All', count: PIPELINES.length, predicate: () => true },
  { id: 'healthy', label: 'Healthy', count: PIPELINES.filter((p) => p.status === 'healthy').length, predicate: (p) => p.status === 'healthy' },
  { id: 'issues', label: 'Issues', count: PIPELINES.filter((p) => p.status === 'degraded' || p.status === 'error').length, predicate: (p) => p.status === 'degraded' || p.status === 'error' },
  { id: 'high-volume', label: 'High volume', count: PIPELINES.filter((p) => p.eventsIn24h >= 200_000).length, predicate: (p) => p.eventsIn24h >= 200_000 },
  { id: 'has-custom', label: 'With custom filters', count: PIPELINES.filter((p) => p.filters.some((f) => !f.systemOwner)).length, predicate: (p) => p.filters.some((f) => !f.systemOwner) },
]

/* ─── Page ─────────────────────────────────────────────────────────────── */

export function DataProcessingPage() {
  const [view, setView] = useState<string>('all')
  const [search, setSearch] = useState('')
  const [openPipeline, setOpenPipeline] = useState<Pipeline | null>(null)

  const filtered = useMemo(() => {
    const v = SAVED_VIEWS.find((s) => s.id === view) ?? SAVED_VIEWS[0]
    return PIPELINES.filter(v.predicate).filter((p) =>
      search ? (p.name + p.description).toLowerCase().includes(search.toLowerCase()) : true
    )
  }, [view, search])

  return (
    <div className="mx-auto w-full max-w-[1600px] px-6 py-6">
      <Header total={filtered.length} />

      <div className="mt-5 grid grid-cols-12 gap-4">
        <div className="col-span-12 lg:col-span-8">
          <ProcessingOverviewCard />
        </div>
        <div className="col-span-12 lg:col-span-4">
          <ProcessingInsightsCard />
        </div>
      </div>

      <div className="mt-5">
        <SavedViewTabs current={view} onChange={setView} />
      </div>

      <Toolbar search={search} onSearch={setSearch} />

      <div className="mt-3 overflow-hidden rounded-xl border border-border bg-card">
        <ListHeader />
        {filtered.map((p) => (
          <PipelineRow key={p.id} pipeline={p} onOpen={() => setOpenPipeline(p)} />
        ))}
        {filtered.length === 0 && (
          <div className="px-6 py-16 text-center text-sm text-muted-foreground">
            No pipelines match this view.
          </div>
        )}
      </div>

      {openPipeline && (
        <PipelineDrawer pipeline={openPipeline} onClose={() => setOpenPipeline(null)} />
      )}
    </div>
  )
}

/* ─── Header ───────────────────────────────────────────────────────────── */

function Header({ total }: { total: number }) {
  return (
    <header className="flex flex-wrap items-end justify-between gap-3">
      <div>
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-semibold tracking-tight">Data processing</h1>
          <span className="rounded-md bg-muted px-2 py-0.5 font-mono text-[11px] tabular-nums text-muted-foreground">
            {total.toLocaleString()} pipelines
          </span>
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          One pipeline per integration. Filters parse, normalize, drop, and enrich events on
          the way to OpenSearch.
        </p>
      </div>
      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm">
          <Upload size={14} className="mr-2" />
          Import filter
        </Button>
        <Button size="sm">
          <Plus size={14} className="mr-2" />
          New custom filter
        </Button>
      </div>
    </header>
  )
}

/* ─── Overview chart ───────────────────────────────────────────────────── */

function ProcessingOverviewCard() {
  const buckets = 60
  const data = useMemo(
    () =>
      Array.from({ length: buckets }, (_, i) =>
        Math.round(2400 + Math.sin(i / 5) * 600 + Math.sin(i / 11) * 200 + (i > 50 ? 400 : 0))
      ),
    []
  )
  const totalIn = PIPELINES.reduce((s, p) => s + p.eventsIn24h, 0)
  const totalOut = PIPELINES.reduce((s, p) => s + p.eventsOut24h, 0)
  const dropPct = totalIn > 0 ? ((totalIn - totalOut) / totalIn) * 100 : 0

  const w = 1000
  const h = 100
  const max = Math.max(...data) * 1.15
  const xs = data.map((_, i) => (i * w) / (data.length - 1))
  const ys = data.map((v) => h - (v / max) * h)
  const linePath = data.reduce((acc, _, i) => {
    if (i === 0) return `M ${xs[i]} ${ys[i]}`
    const prevX = xs[i - 1]
    const prevY = ys[i - 1]
    const cx1 = prevX + (xs[i] - prevX) / 2
    const cx2 = xs[i] - (xs[i] - prevX) / 2
    return `${acc} C ${cx1} ${prevY}, ${cx2} ${ys[i]}, ${xs[i]} ${ys[i]}`
  }, '')
  const areaPath = `${linePath} L ${xs[xs.length - 1]} ${h} L ${xs[0]} ${h} Z`

  return (
    <div className="rounded-xl border border-border bg-card p-6">
      <div className="flex items-baseline justify-between">
        <div>
          <div className="text-[11px] uppercase tracking-wider text-muted-foreground">
            Events processed · last 24 hours
          </div>
          <div className="mt-1 flex items-baseline gap-3">
            <span className="text-3xl font-semibold tabular-nums">{formatCount(totalOut)}</span>
            <span className="text-sm text-muted-foreground">
              of {formatCount(totalIn)} ingested
              <span className="mx-2 text-border">·</span>
              <span className="text-foreground">{dropPct.toFixed(1)}%</span> dropped by filters
            </span>
          </div>
        </div>
      </div>

      <svg viewBox={`0 0 ${w} ${h}`} className="mt-4 h-24 w-full" preserveAspectRatio="none">
        <defs>
          <linearGradient id="dpGrad" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="rgb(34 211 238)" stopOpacity="0.28" />
            <stop offset="100%" stopColor="rgb(34 211 238)" stopOpacity="0" />
          </linearGradient>
        </defs>
        <path d={areaPath} fill="url(#dpGrad)" />
        <path
          d={linePath}
          fill="none"
          stroke="rgb(34 211 238)"
          strokeOpacity="0.85"
          strokeWidth="1.75"
          strokeLinejoin="round"
          strokeLinecap="round"
        />
      </svg>

      <div className="mt-2 flex justify-between text-[10px] text-muted-foreground">
        <span>24h ago</span>
        <span>12h ago</span>
        <span>now</span>
      </div>
    </div>
  )
}

/* ─── Insights ─────────────────────────────────────────────────────────── */

function ProcessingInsightsCard() {
  const error = PIPELINES.filter((p) => p.status === 'error').length
  const degraded = PIPELINES.filter((p) => p.status === 'degraded').length

  return (
    <div className="flex h-full flex-col gap-3 rounded-xl border border-border bg-card p-5">
      <div className="flex items-center gap-2">
        <Sparkles size={14} className="text-fuchsia-500" />
        <h3 className="text-sm font-semibold">Pipeline health</h3>
      </div>

      {error > 0 && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/5 p-3 text-xs leading-relaxed">
          <span className="font-medium text-foreground">
            {error} pipeline{error === 1 ? '' : 's'} failing
          </span>{' '}
          — GitHub auth token expired.{' '}
          <button className="text-primary hover:underline">Reconnect</button>
        </div>
      )}

      {degraded > 0 && (
        <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-xs leading-relaxed">
          <span className="font-medium text-foreground">
            {degraded} pipeline{degraded === 1 ? '' : 's'} degraded
          </span>{' '}
          — Microsoft 365 throttling, ~142 events deferred.{' '}
          <button className="text-primary hover:underline">View</button>
        </div>
      )}

      <div className="rounded-lg border border-fuchsia-500/30 bg-gradient-to-br from-fuchsia-500/10 via-violet-500/5 to-transparent p-3 text-xs leading-relaxed">
        <span className="font-medium text-foreground">12 custom filters</span> active across 6
        pipelines. Top contributor:{' '}
        <span className="font-medium">pfSense allow-noise drop</span> (6,470 events/24h).
      </div>
    </div>
  )
}

/* ─── Saved view tabs ──────────────────────────────────────────────────── */

function SavedViewTabs({ current, onChange }: { current: string; onChange: (id: string) => void }) {
  return (
    <div className="flex flex-wrap items-center gap-1 border-b border-border">
      {SAVED_VIEWS.map((v) => {
        const active = current === v.id
        return (
          <button
            key={v.id}
            onClick={() => onChange(v.id)}
            className={cn(
              'group relative flex items-center gap-2 px-3 py-2 text-xs transition-colors',
              active ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'
            )}
          >
            <span>{v.label}</span>
            <span
              className={cn(
                'rounded-md px-1.5 py-0.5 font-mono text-[10px] tabular-nums',
                active ? 'bg-primary/15 text-primary' : 'bg-muted text-muted-foreground'
              )}
            >
              {v.count}
            </span>
            {active && <span className="absolute inset-x-2 -bottom-px h-0.5 rounded-full bg-primary" />}
          </button>
        )
      })}
    </div>
  )
}

/* ─── Toolbar ──────────────────────────────────────────────────────────── */

function Toolbar({ search, onSearch }: { search: string; onSearch: (s: string) => void }) {
  return (
    <div className="mt-3 flex flex-wrap items-center gap-2">
      <div className="relative min-w-[280px] flex-1">
        <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
        <Input
          value={search}
          onChange={(e) => onSearch(e.target.value)}
          placeholder="Search pipelines, integrations, filters…"
          className="h-9 pl-9"
        />
      </div>
      <Button variant="outline" size="sm">
        <ListFilter size={14} className="mr-2" />
        Filters
      </Button>
      <button
        title="Refresh"
        className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-muted-foreground hover:bg-muted hover:text-foreground"
      >
        <RefreshCw size={14} />
      </button>
    </div>
  )
}

/* ─── List ─────────────────────────────────────────────────────────────── */

const COLS = '40px 1fr 90px 100px 110px 110px 100px 36px'

function ListHeader() {
  return (
    <div
      className="grid items-center gap-3 border-b border-border bg-muted/40 px-4 py-2 text-[10px] uppercase tracking-wider text-muted-foreground"
      style={{ gridTemplateColumns: COLS }}
    >
      <div />
      <div>Pipeline</div>
      <div>Status</div>
      <div className="text-right">Rate</div>
      <div className="text-right">24h in</div>
      <div className="text-right">Drop %</div>
      <div className="text-right">Filters</div>
      <div />
    </div>
  )
}

function PipelineRow({ pipeline: p, onOpen }: { pipeline: Pipeline; onOpen: () => void }) {
  const st = STATUS_META[p.status]
  const dropPct = p.eventsIn24h > 0 ? ((p.eventsIn24h - p.eventsOut24h) / p.eventsIn24h) * 100 : 0
  const customFilters = p.filters.filter((f) => !f.systemOwner).length

  return (
    <div
      onClick={onOpen}
      className="group grid cursor-pointer items-center gap-3 border-b border-border px-4 py-3 text-xs hover:bg-muted/40 last:border-b-0"
      style={{ gridTemplateColumns: COLS }}
    >
      <LogoTile src={LOGO(p.integrationId)} alt={p.name} size={32} />
      <div className="min-w-0">
        <div className="flex items-center gap-2">
          <span className="truncate text-sm font-medium">{p.name}</span>
        </div>
        <div className="truncate text-[11px] text-muted-foreground">{p.description}</div>
      </div>
      <div>
        <span className="inline-flex items-center gap-1.5 text-[11px] text-muted-foreground">
          <span className={cn('h-1.5 w-1.5 rounded-full', st.dot)} />
          {st.label}
        </span>
      </div>
      <div className="text-right font-mono tabular-nums">
        {p.rate > 0 ? (
          <span>
            {p.rate.toLocaleString()}
            <span className="ml-0.5 text-[10px] text-muted-foreground">e/s</span>
          </span>
        ) : (
          <span className="text-muted-foreground">—</span>
        )}
      </div>
      <div className="text-right font-mono tabular-nums">
        {p.eventsIn24h > 0 ? formatCount(p.eventsIn24h) : <span className="text-muted-foreground">—</span>}
      </div>
      <div className={cn('text-right font-mono tabular-nums', dropPct > 5 ? 'text-amber-500' : 'text-muted-foreground')}>
        {p.eventsIn24h > 0 ? `${dropPct.toFixed(1)}%` : '—'}
      </div>
      <div className="text-right text-[11px]">
        <span className="font-mono">{p.filters.length}</span>
        {customFilters > 0 && (
          <span className="ml-1 text-emerald-500">+{customFilters}</span>
        )}
      </div>
      <div className="flex justify-end opacity-0 group-hover:opacity-100">
        <button
          onClick={(e) => e.stopPropagation()}
          className="flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-background hover:text-foreground"
        >
          <MoreHorizontal size={14} />
        </button>
      </div>
    </div>
  )
}

function LogoTile({ src, alt, size }: { src: string; alt: string; size: number }) {
  return (
    <div
      className="flex shrink-0 items-center justify-center overflow-hidden rounded-md border border-border bg-muted/40 p-1"
      style={{ width: size, height: size }}
    >
      <img src={src} alt={alt} className="max-h-full max-w-full object-contain" loading="lazy" />
    </div>
  )
}

/* ─── Drawer ───────────────────────────────────────────────────────────── */

type Tab = 'overview' | 'filters' | 'history'

function PipelineDrawer({ pipeline: p, onClose }: { pipeline: Pipeline; onClose: () => void }) {
  const [tab, setTab] = useState<Tab>('filters')
  const st = STATUS_META[p.status]
  const dropPct = p.eventsIn24h > 0 ? ((p.eventsIn24h - p.eventsOut24h) / p.eventsIn24h) * 100 : 0

  return (
    <div className="fixed inset-0 z-50 flex items-stretch justify-end bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div
        className="flex w-full max-w-[920px] flex-col overflow-hidden border-l border-border bg-card shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="border-b border-border px-6 py-4">
          <div className="flex items-start justify-between gap-4">
            <div className="flex min-w-0 flex-1 items-start gap-3">
              <LogoTile src={LOGO(p.integrationId)} alt={p.name} size={48} />
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
                  <span className="font-mono">{p.id}</span>
                  <span>·</span>
                  <span>modified {relativeTime(p.modifiedAt)}</span>
                </div>
                <h2 className="mt-0.5 truncate text-lg font-semibold">{p.name}</h2>
                <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
                  {p.description}
                </p>
                <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px]">
                  <span className="inline-flex items-center gap-1.5 text-muted-foreground">
                    <span className={cn('h-1.5 w-1.5 rounded-full', st.dot)} />
                    {st.label}
                  </span>
                  {p.eventsIn24h > 0 && (
                    <>
                      <span className="text-border">·</span>
                      <span className="text-muted-foreground">
                        <span className="font-mono">{p.rate}</span> e/s
                      </span>
                      <span className="text-border">·</span>
                      <span className="text-muted-foreground">
                        <span className="font-mono">{dropPct.toFixed(1)}%</span> dropped
                      </span>
                    </>
                  )}
                </div>
              </div>
            </div>
            <button
              onClick={onClose}
              className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"
            >
              <X size={16} />
            </button>
          </div>

          {p.lastError && (
            <div className="mt-3 rounded-lg border border-red-500/30 bg-red-500/5 p-3 text-xs">
              <div className="flex items-center gap-2 font-medium text-red-600 dark:text-red-300">
                <AlertTriangle size={13} />
                Last error
              </div>
              <p className="mt-1 text-muted-foreground">{p.lastError}</p>
            </div>
          )}

          <div className="mt-4 flex flex-wrap items-center gap-2">
            <Button size="sm">
              <Plus size={13} className="mr-1.5" />
              Add custom filter
            </Button>
            {p.status === 'paused' || p.status === 'error' ? (
              <Button size="sm" variant="outline">
                <Play size={13} className="mr-1.5" />
                Resume
              </Button>
            ) : (
              <Button size="sm" variant="outline">
                <Pause size={13} className="mr-1.5" />
                Pause
              </Button>
            )}
            <Button size="sm" variant="outline">
              <ExternalLink size={13} className="mr-1.5" />
              View processed events
            </Button>
          </div>
        </header>

        <nav className="flex items-center gap-1 border-b border-border px-6">
          <DrawerTab id="filters" current={tab} onChange={setTab} icon={FilterIcon}>
            Filters
            <span className="ml-1.5 rounded bg-muted px-1.5 py-0.5 font-mono text-[10px]">
              {p.filters.length}
            </span>
          </DrawerTab>
          <DrawerTab id="overview" current={tab} onChange={setTab} icon={Sparkles}>
            Overview
          </DrawerTab>
          <DrawerTab id="history" current={tab} onChange={setTab} icon={History}>
            History
          </DrawerTab>
        </nav>

        <div className="flex-1 overflow-y-auto bg-muted/20">
          {tab === 'filters' && <FiltersTab pipeline={p} />}
          {tab === 'overview' && <OverviewTab pipeline={p} />}
          {tab === 'history' && <HistoryTab pipeline={p} />}
        </div>
      </div>
    </div>
  )
}

function DrawerTab({
  id,
  current,
  onChange,
  icon: Icon,
  children,
}: {
  id: Tab
  current: Tab
  onChange: (t: Tab) => void
  icon: LucideIcon
  children: React.ReactNode
}) {
  const active = id === current
  return (
    <button
      onClick={() => onChange(id)}
      className={cn(
        'relative flex items-center gap-1.5 px-3 py-2.5 text-xs transition-colors',
        active ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'
      )}
    >
      <Icon size={13} />
      {children}
      {active && <span className="absolute inset-x-2 -bottom-px h-0.5 rounded-full bg-primary" />}
    </button>
  )
}

/* ─── Drawer: Filters ──────────────────────────────────────────────────── */

function FiltersTab({ pipeline: p }: { pipeline: Pipeline }) {
  const [openFilter, setOpenFilter] = useState<string | null>(p.filters[0]?.id ?? null)

  return (
    <div className="p-6">
      <div className="mb-3 text-[11px] text-muted-foreground">
        Filters run <span className="font-medium text-foreground">top to bottom</span>. Each event
        passes through every filter in order. Custom filters can be reordered; system filters
        cannot.
      </div>

      <ol className="space-y-2">
        {p.filters.map((f, i) => (
          <FilterCard
            key={f.id}
            filter={f}
            index={i + 1}
            open={openFilter === f.id}
            onToggle={() => setOpenFilter(openFilter === f.id ? null : f.id)}
          />
        ))}
      </ol>

      <div className="mt-4 flex justify-center">
        <button className="inline-flex items-center gap-2 rounded-md border border-dashed border-border bg-card px-4 py-2 text-xs text-muted-foreground hover:bg-muted hover:text-foreground">
          <Plus size={12} />
          Insert custom filter
        </button>
      </div>

      <div className="mt-4 flex items-center justify-between rounded-lg border border-border bg-card px-4 py-3 text-xs">
        <span className="inline-flex items-center gap-2">
          <Zap size={13} className="text-emerald-500" />
          <span className="font-medium">Output</span>
          <span className="text-muted-foreground">→ OpenSearch index</span>
        </span>
        <span className="font-mono text-[11px] text-muted-foreground">
          {formatCount(p.eventsOut24h)} events / 24h
        </span>
      </div>
    </div>
  )
}

function FilterCard({
  filter: f,
  index,
  open,
  onToggle,
}: {
  filter: PipelineFilter
  index: number
  open: boolean
  onToggle: () => void
}) {
  const km = FILTER_KIND_META[f.kind]
  const KIcon = km.icon
  return (
    <li className="overflow-hidden rounded-lg border border-border bg-card">
      <button
        onClick={onToggle}
        className="flex w-full items-center gap-3 px-4 py-2.5 text-left transition-colors hover:bg-muted/40"
      >
        <span
          className={cn(
            'shrink-0 cursor-grab text-muted-foreground/50',
            f.systemOwner && 'cursor-not-allowed opacity-30'
          )}
          onClick={(e) => e.stopPropagation()}
          title={f.systemOwner ? 'System filter — order is fixed' : 'Drag to reorder'}
        >
          <GripVertical size={12} />
        </span>
        <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-muted font-mono text-[11px] tabular-nums text-muted-foreground">
          {index}
        </span>
        <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-muted/60">
          <KIcon size={13} className={km.tone} />
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="truncate text-sm font-medium">{f.name}</span>
            {f.systemOwner ? (
              <span className="inline-flex items-center gap-1 rounded bg-muted px-1.5 py-0.5 text-[9px] uppercase text-muted-foreground">
                <Lock size={9} />
                system
              </span>
            ) : (
              <span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-[9px] uppercase text-emerald-600 ring-1 ring-emerald-500/30 dark:text-emerald-300">
                custom
              </span>
            )}
            <span className={cn('text-[10px] uppercase tracking-wider', km.tone)}>
              {km.label}
            </span>
          </div>
          <div className="truncate text-[11px] text-muted-foreground">{f.description}</div>
        </div>
        {f.matched24h !== undefined && (
          <span className="shrink-0 font-mono text-[11px] text-muted-foreground">
            {formatCount(f.matched24h)}
          </span>
        )}
      </button>
      {open && (
        <div className="border-t border-border px-4 py-3">
          <div className="mb-1.5 text-[10px] uppercase tracking-wider text-muted-foreground">
            Configuration
          </div>
          <pre className="overflow-x-auto rounded-md bg-muted/40 p-3 font-mono text-[11px] leading-relaxed">
            {f.preview}
          </pre>
          {!f.systemOwner && (
            <div className="mt-3 flex items-center gap-3 text-[11px]">
              <button className="text-primary hover:underline">Edit</button>
              <button className="text-primary hover:underline">Duplicate</button>
              <button className="text-red-500 hover:underline">Delete</button>
              <button className="ml-auto inline-flex items-center gap-1 text-muted-foreground hover:text-foreground">
                <Copy size={11} />
                Copy
              </button>
            </div>
          )}
          {f.systemOwner && (
            <div className="mt-3 flex items-center gap-2 text-[11px] text-muted-foreground">
              <Lock size={11} />
              System filter — read-only.{' '}
              <button className="text-primary hover:underline">Override with custom filter</button>
            </div>
          )}
        </div>
      )}
    </li>
  )
}

/* ─── Drawer: Overview ─────────────────────────────────────────────────── */

function OverviewTab({ pipeline: p }: { pipeline: Pipeline }) {
  const dropPct = p.eventsIn24h > 0 ? ((p.eventsIn24h - p.eventsOut24h) / p.eventsIn24h) * 100 : 0
  return (
    <div className="grid grid-cols-3 gap-4 p-6">
      <div className="col-span-2 space-y-4">
        <Section title="Throughput · last 24 hours">
          <div className="grid grid-cols-3 gap-3 text-xs">
            <Stat label="Events in" value={formatCount(p.eventsIn24h)} tone="text-sky-500" />
            <Stat label="Dropped" value={`${dropPct.toFixed(1)}%`} tone={dropPct > 5 ? 'text-amber-500' : 'text-muted-foreground'} />
            <Stat label="Events out" value={formatCount(p.eventsOut24h)} tone="text-emerald-500" />
          </div>
          <div className="mt-3 flex items-center gap-2 text-[11px] text-muted-foreground">
            <Database size={11} />
            <span>Source</span>
            <ArrowRight size={11} />
            <span>{p.filters.length} filters</span>
            <ArrowRight size={11} />
            <span>OpenSearch index</span>
          </div>
        </Section>

        <Section title="Filter mix">
          <ul className="space-y-1.5">
            {Object.entries(
              p.filters.reduce<Record<string, number>>((acc, f) => {
                acc[f.kind] = (acc[f.kind] ?? 0) + 1
                return acc
              }, {})
            ).map(([k, count]) => {
              const meta = FILTER_KIND_META[k as FilterKind]
              const Icon = meta.icon
              return (
                <li key={k} className="flex items-center justify-between text-xs">
                  <span className="inline-flex items-center gap-2">
                    <Icon size={12} className={meta.tone} />
                    {meta.label}
                  </span>
                  <span className="font-mono tabular-nums text-muted-foreground">{count}</span>
                </li>
              )
            })}
          </ul>
        </Section>
      </div>

      <aside className="col-span-1 space-y-4">
        <KeyValueCard
          title="Pipeline"
          rows={[
            ['ID', <span className="font-mono">{p.id}</span>],
            ['Status', STATUS_META[p.status].label],
            ['Modified', relativeTime(p.modifiedAt)],
          ]}
        />

        <div className="rounded-lg border border-border bg-card p-4">
          <div className="mb-2 text-[11px] uppercase tracking-wider text-muted-foreground">
            Custom filters
          </div>
          <div className="text-xs">
            <span className="font-mono text-foreground">
              {p.filters.filter((f) => !f.systemOwner).length}
            </span>{' '}
            of <span className="font-mono">{p.filters.length}</span> filters are custom.
          </div>
          {p.filters.filter((f) => !f.systemOwner).length === 0 && (
            <button className="mt-2 text-[11px] text-primary hover:underline">
              + Add your first custom filter
            </button>
          )}
        </div>
      </aside>
    </div>
  )
}

/* ─── Drawer: History ──────────────────────────────────────────────────── */

function HistoryTab({ pipeline: p }: { pipeline: Pipeline }) {
  const events = [
    { ts: hr(8), who: 'jsmith', what: `enabled custom filter "Drop verbose group policy events"` },
    { ts: days(2), who: 'system', what: `system filter "Parse Windows Event XML" updated to v3` },
    { ts: days(7), who: 'mthomas', what: 'reordered custom filters' },
    { ts: days(15), who: 'jsmith', what: 'created pipeline' },
  ]
  return (
    <div className="p-6">
      <ol className="relative space-y-4 border-l border-border pl-6">
        {events.map((e, i) => (
          <li key={i} className="relative">
            <span className="absolute -left-[27px] top-1 h-3 w-3 rounded-full border-2 border-card bg-primary" />
            <div className="text-xs">
              <span className="font-mono">{e.who}</span> {e.what}
            </div>
            <div className="text-[10px] text-muted-foreground">{relativeTime(e.ts)}</div>
          </li>
        ))}
      </ol>
      <div className="mt-4 text-[10px] text-muted-foreground">Pipeline modified at: {relativeTime(p.modifiedAt)}</div>
    </div>
  )
}

/* ─── Small parts ──────────────────────────────────────────────────────── */

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <h4 className="mb-3 text-sm font-semibold">{title}</h4>
      {children}
    </div>
  )
}

function KeyValueCard({
  title,
  rows,
}: {
  title: string
  rows: [string, React.ReactNode][]
}) {
  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <div className="mb-2 text-[11px] uppercase tracking-wider text-muted-foreground">{title}</div>
      <dl className="grid grid-cols-[100px_1fr] gap-y-2 text-xs">
        {rows.map(([k, v]) => (
          <Row key={k} k={k}>
            {v}
          </Row>
        ))}
      </dl>
    </div>
  )
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <div className="rounded-md border border-border bg-background/40 px-3 py-2">
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className={cn('mt-0.5 font-mono text-base font-semibold tabular-nums', tone)}>
        {value}
      </div>
    </div>
  )
}

function Row({ k, children }: { k: string; children: React.ReactNode }) {
  return (
    <>
      <dt className="text-muted-foreground">{k}</dt>
      <dd className="break-words">{children}</dd>
    </>
  )
}

/* ─── Helpers ──────────────────────────────────────────────────────────── */

function relativeTime(iso: string) {
  if (!iso) return '—'
  const diff = NOW - new Date(iso).getTime()
  const m = Math.round(diff / 60_000)
  if (m < 1) return 'just now'
  if (m < 60) return `${m}m ago`
  const h = Math.round(m / 60)
  if (h < 24) return `${h}h ago`
  return `${Math.round(h / 24)}d ago`
}

function formatCount(n: number) {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`
  return n.toString()
}
