name: Docker Image Golang

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      binary:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Running Tests
        working-directory: ./${{inputs.directory}}
        run: go test -v ./...
  
      - name: Build Binary
        working-directory: ./${{inputs.directory}}
        run: go build -o ${{inputs.binary}} -v .
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{inputs.directory}}
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}