# Elasticsearch filter, version 3.0.0
# Fields based on https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-module-elasticsearch.html
# and filebeat fields.yml version 7.13.4 oss
# Support logs from elasticsearch 7++
# Filter Input requirements -> fileset: datatype
#                              server: plain text
# 1. Parsing the json from beats
# 2. Parsing the message field containing the elasticsearch log
pipeline:
  - dataTypes:
      - elasticsearch
    steps:
      - json:
          source: raw
      - rename:
          from:
            - log.url
          to: origin.url
      - rename:
          from:
            - log.log.file.path
          to: origin.file
      - rename:
          from:
            - log.host.ip
          to: log.local.ips
      - rename:
          from:
            - log.host.mac
          to: log.local.macs
      - rename:
          from:
            - log.host.hostname
          to: origin.host
      - rename:
          from:
            - log.event.dataset
          to: action
      - rename:
          from:
            - log.agent.version
          to: log.agentVersion
      - rename:
          from:
            - log.host.os.kernel
          to: log.osVersion
      - rename:
          from:
            - log.host.os.type
          to: log.osType
      - rename:
          from:
            - log.host.architecture
          to: log.cpuArchitecture
      - cast:
          to: '[]string'
          fields:
            - log.local.ips
      - cast:
          to: '[]string'
          fields:
            - log.local.macs
      - grok:
          patterns:
            - fieldName: deviceTime
              pattern: '\[{{.data}}\]'
            - fieldName: log.level
              pattern: '\[{{.data}}\]'
            - fieldName: log.component
              pattern: '\[{{.data}}\]'
            - fieldName: log.nodeName
              pattern: '\[{{.data}}\]'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: log.message
      - trim:
          function: prefix
          substring: '['
          fields:
            - deviceTime
            - log.level
            - log.component
            - log.nodeName
          where:
            variables:
              - get: log.msg
                as: msgflag
                ofType: string
            expression: msgflag_ok == true
      - trim:
          function: suffix
          substring: ']'
          fields:
            - deviceTime
            - log.level
            - log.component
            - log.nodeName
          where:
            variables:
              - get: log.msg
                as: msgflag
                ofType: string
            expression: msgflag_ok == true
      - reformat:
          fields:
            - deviceTime
          function: time
          fromFormat: '2022-01-20T22:52:07,431'
          toFormat: '2024-09-23T15:57:40.338364445Z'
          where:
            variables:
              - get: deviceTime
                as: dt
                ofType: string
            expression: dt_ok == true
      # Begin parsing when message comes in json format
      - json:
          source: log.message
          where:
            variables:
              - get: log.msg
                as: msgflag
                ofType: string
            expression: msgflag_ok == false
      # Rename audit fields from json
      - rename:
          from:
            - log.audit_format_version
          to: log.auditFormatVersion
      - rename:
          from:
            - log.audit_category
          to: log.auditCategory
      - rename:
          from:
            - log.audit_node_host_address
          to: log.auditNodeHostAddress
      - rename:
          from:
            - log.audit_node_host_name
          to: log.auditNodeHostName
      - rename:
          from:
            - log.audit_request_layer
          to: log.auditRequestLayer
      - rename:
          from:
            - log.audit_request_origin
          to: log.auditRequestOrigin
      - rename:
          from:
            - log.audit_request_effective_user_is_admin
          to: log.auditRequestEffectiveUserIsAdmin
      - rename:
          from:
            - log.audit_request_effective_user
          to: log.auditRequestEffectiveUser
      - rename:
          from:
            - log.audit_rest_request_path
          to: log.auditRestRequestPath
      - rename:
          from:
            - log.audit_rest_request_params
          to: log.auditRestRequestParams
      - rename:
          from:
            - log.audit_rest_request_headers
          to: log.auditRestRequestHeaders
      - rename:
          from:
            - log.audit_request_initiating_user
          to: log.auditRequestInitiatingUser
      - rename:
          from:
            - log.audit_request_body
          to: log.auditRequestBody
      - rename:
          from:
            - log.audit_rest_request_method
          to: log.auditRestRequestMethod
      - rename:
          from:
            - log.audit_request_exception_stacktrace
          to: log.auditRequestExceptionStacktrace
      - rename:
          from:
            - log.audit_trace_task_id
          to: log.auditTraceTaskId
      - rename:
          from:
            - log.audit_transport_headers
          to: log.auditTransportHeaders
      - rename:
          from:
            - log.audit_transport_request_type
          to: log.auditTransportRequestType
      - rename:
          from:
            - log.audit_trace_indices
          to: log.auditTraceIndices
      - rename:
          from:
            - log.audit_trace_resolved_indices
          to: log.auditTraceResolvedIndices
      - rename:
          from:
            - log.audit_trace_doc_types
          to: log.auditTraceDocTypes
      - rename:
          from:
            - log.audit_trace_task_parent_id
          to: log.auditTraceTaskParentId
      - rename:
          from:
            - log.audit_request_privilege
          to: log.auditRequestPrivilege
      - rename:
          from:
            - log.audit_compliance_operation
          to: log.auditComplianceOperation
      - rename:
          from:
            - log.node.id
            - log.audit_node_id
          to: log.nodeId
      - rename:
          from:
            - log.node.name
            - log.audit_node_name
          to: log.nodeName
      - rename:
          from:
            - log.cluster.name
            - log.audit_cluster_name
          to: log.clusterName
      - rename:
          from:
            - log.cluster.uuid
          to: log.clusterUuid
      # Adding severity based on log.level
      - add:
          function: 'string'
          params:
            key: severity
            value: 'high'
          where:
            variables:
              - get: log.level
                as: lvl
                ofType: string
            expression: lvl_ok == true && (lvl == "CRITICAL" || lvl == "FATAL" || lvl == "ERROR")
      - add:
          function: 'string'
          params:
            key: severity
            value: 'medium'
          where:
            variables:
              - get: log.level
                as: lvl
                ofType: string
            expression: lvl_ok == true && lvl == "WARN"
      - add:
          function: 'string'
          params:
            key: severity
            value: 'low'
          where:
            variables:
              - get: log.level
                as: lvl
                ofType: string
            expression: lvl_ok == true && (lvl == "INFO" || lvl == "DEBUG" || lvl == "TRACE")

      # Removing unused fields
      - delete:
          fields:
            - log.service
            - log.metadata
            - log.agent
            - log.host
            - log.event
            - log.ecs
            - log.log
            - log.fileset
