# Redis module filter, version 3.0.0
# Filter Input requirements -> fileset: datatype
#                              log: plain text
# 
# Documentations
# 1- https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-module-redis.html
# 2- https://www.elastic.co/guide/en/beats/filebeat/7.13/exported-fields-redis.html
# 3- https://redis.io/docs/latest/operate/rs/clusters/logging/redis-slow-log/
# 4- https://build47.com/redis-log-format-levels/
# Implementation
# 1. Parsing the json from beats
# 2. Parsing the message field containing the redis log
pipeline:
  - dataTypes:
      - redis
    steps:
      - json:
          source: raw
      
      # Parse message field in plain text format
      - grok:
          patterns:
            - fieldName: log.pidRole
              pattern: '((\d+)?:([A-Z])?)|\[{{.data}}\]'
            - fieldName: log.deviceTime
              pattern: '{{.monthDay}}{{.space}}{{.monthName}}{{.space}}{{.year}}{{.space}}{{.time}}'
            - fieldName: log.logLevel
              pattern: '(.)|(-)(\*)(#)'
            - fieldName: log.actionResult
              pattern: '{{.greedy}}'
          source: log.message

      # Parse beats field
      - rename:
          from:
            - log.log.file.path
          to: local.file
      - rename:
          from:
            - log.host.ip
          to: local.ips
      - rename:
          from:
            - log.host.mac
          to: local.macs
      - rename:
          from:
            - log.host.hostname
          to: local.host
      - rename:
          from:
            - log.event.dataset
          to: action
      - rename:
          from:
            - log.agent.version
          to: log.agentVersion
      - rename:
          from:
            - log.host.os.kernel
          to: log.osVersion
      - rename:
          from:
            - log.host.os.type
          to: log.osType
      - rename:
          from:
            - log.host.architecture
          to: log.cpuArchitecture

      # Fields conversions
      - cast:
          to: "[]string"
          fields:
            - local.ips
      - cast:
          to: "[]string"
          fields:
            - local.macs

      # Removing unused fields
      - delete:
          fields:
            - log.service
            - log.metadata
            - log.log.offset
            - log.agent
            - log.host
            - log.event
            - log.ecs
            - log.log.file