# CISCO ASA filter, version 3.0.0
# Based on examples provided and https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog.html
# Filter Input requirements -> Syslog
#
# 1. Parsing the message field containing the Cisco ASA log
pipeline:
  - dataTypes:
      - firewall-cisco-asa
    steps:
      # Common ASA fields
      - grok:
          patterns:
            - fieldName: log.syslogPri
              pattern: '(\<{{.integer}}\>)'
            - fieldName: log.ciscoTime
              pattern: '({{.day}}\s)?{{.monthName}}\s{{.monthDay}}\s{{.year}}\s{{.time}}'
            - fieldName: local.ip
              pattern: '{{.ipv4}}|{{.ipv6}}|{{.hostname}}'
            - fieldName: log.asaHeader
              pattern: '{{.data}}ASA-'
            - fieldName: log.severity
              pattern: '{{.integer}}'
            - fieldName: log.messageId
              pattern: '-{{.integer}}'
            - fieldName: log.ciscoSeparator
              pattern: '\:{{.space}}'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: raw
      - grok:
          patterns:
            - fieldName: log.ciscoTime
              pattern: '({{.day}}\s)?{{.monthName}}\s{{.monthDay}}\s{{.year}}\s{{.time}}'
            - fieldName: local.ip
              pattern: '{{.ipv4}}|{{.ipv6}}|{{.hostname}}'
            - fieldName: log.asaHeader
              pattern: '{{.data}}ASA-'
            - fieldName: log.severity
              pattern: '{{.integer}}'
            - fieldName: log.messageId
              pattern: '-{{.integer}}'
            - fieldName: log.ciscoSeparator
              pattern: '\:{{.space}}'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: raw
      # Removing unwanted prefixes
      - trim:
          function: prefix
          substring: '-'
          fields:
            - log.messageId
      # Field conversions
      - cast:
          fields:
            - log.messageId
          to: int
      # Begining specific message parsing
      #......................................................................#
      # ASA-2-106001
      - grok:
          patterns:
            - fieldName: log.direction
              pattern: '{{.word}}'
            - fieldName: protocol
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: 'connection'
            - fieldName: actionResult
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: 'from'
            - fieldName: from.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: from.port
              pattern: '/{{.integer}}'
            - fieldName: log.irrelevant
              pattern: 'to'
            - fieldName: to.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: to.port
              pattern: '/{{.integer}}'
            - fieldName: log.irrelevant
              pattern: 'flags'
            - fieldName: log.flags
              pattern: '{{.data}}\s'
            - fieldName: log.irrelevant
              pattern: 'on\sinterface'
            - fieldName: log.interface
              pattern: '{{.greedy}}'
          source: log.msg

      - trim:
          function: prefix
          substring: '/'
          fields:
            - from.port
            - to.port

      #......................................................................#
      #ASA-2-106017
      - grok:
          patterns:
            - fieldName: actionResult
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: 'IP\sdue\sto'
            - fieldName: action
              pattern: '{{.greedy}}from'
            - fieldName: from.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: log.irrelevant
              pattern: 'to'
            - fieldName: to.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
          source: log.msg
      - trim:
          function: suffix
          substring: 'from'
          fields:
            - action
      #......................................................................#
      # ASA-1-106021
      - grok:
          patterns:
            - fieldName: actionResult
              pattern: '{{.word}}'
            - fieldName: action
              pattern: '{{.greedy}}from'
            - fieldName: from.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: log.irrelevant
              pattern: 'to'
            - fieldName: to.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: log.irrelevant
              pattern: 'on\sinterface'
            - fieldName: log.interface
              pattern: '{{.greedy}}'
          source: log.msg
      - trim:
          function: suffix
          substring: 'from'
          fields:
            - action
      
      #......................................................................#
      # ASA-2-106101
      - grok:
          patterns:
            - fieldName: action
              pattern: 'Number of cached deny-flows for ACL log has reached limit'
            - fieldName: log.rest
              pattern: '{{.greedy}}'
          source: log.msg
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: 'Number of cached'
            - fieldName: actionResult
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: '{{.greedy}}'
          source: action
      # Parsing the limit number
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: '\('
            - fieldName: log.numFlows
              pattern: '{{.integer}}'
            - fieldName: log.irrelevant
              pattern: '{{.greedy}}'
          source: log.rest
      # Field conversions
      - cast:
          fields:
            - log.numFlows
          to: int
      
      #......................................................................#
      # ASA-6-106102,106103
      # First variant
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: 'access-list'
            - fieldName: log.accessList
              pattern: '{{.data}}\s'
            - fieldName: action
              pattern: '{{.word}}'
            - fieldName: protocol
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: 'for user'
            - fieldName: local.user
              pattern: '(''{{.data}}''|{{.data}})\s'
            - fieldName: log.srcInterface
              pattern: '{{.data}}/'
            - fieldName: from.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: from.port
              pattern: '{{.integer}}'
            - fieldName: log.dstInterface
              pattern: '{{.data}}/'
            - fieldName: to.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: to.port
              pattern: '{{.integer}}'
            - fieldName: log.irrelevant
              pattern: 'hit-cnt'
            - fieldName: log.hitCount
              pattern: '{{.integer}}'
            - fieldName: log.rest
              pattern: '{{.greedy}}'
          source: log.msg
      # Second variant
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: 'access-list'
            - fieldName: log.accessList
              pattern: '{{.data}}\s'
            - fieldName: action
              pattern: '{{.word}}'
            - fieldName: protocol
              pattern: '{{.word}}'
            - fieldName: log.irrelevant
              pattern: 'for user'
            - fieldName: local.user
              pattern: '(''{{.data}}''|{{.data}})\s'
            - fieldName: log.srcInterface
              pattern: '{{.data}}/'
            - fieldName: from.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: from.port
              pattern: '\({{.data}}\)'
            - fieldName: log.irrelevant
              pattern: '-\>'
            - fieldName: log.dstInterface
              pattern: '{{.data}}/'
            - fieldName: to.ip
              pattern: '({{.ipv4}}|{{.ipv6}})'
            - fieldName: to.port
              pattern: '\({{.data}}\)'
            - fieldName: log.irrelevant
              pattern: 'hit-cnt'
            - fieldName: log.hitCount
              pattern: '{{.integer}}'
            - fieldName: log.rest
              pattern: '{{.greedy}}'
          source: log.msg
      - trim:
          function: suffix
          substring: '/'
          fields:
            - log.srcInterface
            - log.dstInterface
      - trim:
          function: prefix
          substring: ''''
          fields:
            - local.user
      - trim:
          function: suffix
          substring: ''''
          fields:
            - local.user
      - trim:
          function: prefix
          substring: '('
          fields:
            - from.port
            - to.port
      - trim:
          function: suffix
          substring: ')'
          fields:
            - from.port
            - to.port
      
      #......................................................................#
      # Common field conversions
      - cast:
          fields:
            - from.port
            - to.port
          to: int
      # Removing unused fields
      - delete:
          fields:
            - log.asaHeader
            - log.ciscoSeparator
            - log.irrelevant
            - log.syslogPri
            - log.rest
