# CISCO Meraki filter, version 3.0.0
# Based on https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples
# https://documentation.cysiv.com/articles/#!data-source-onboarding-device-configuration-reference/cisco-meraki-reference-information-and-cim-mapping
#
# Filter Input requirements -> Syslog
#
# 1. Parsing the message field
pipeline:
  - dataTypes:
      - firewall-meraki
    steps:
      # Header fields
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: '(\<{{.integer}}\>)'
            - fieldName: log.ciscoTime
              pattern: '{{.monthName}}\s{{.monthDay}}\s{{.year}}\s{{.time}}'
            - fieldName: log.serverIp
              pattern: '{{.ipv4}}|{{.ipv6}}|{{.hostname}}(\s)?\:'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: raw
      - grok:
          patterns:
            - fieldName: log.ciscoTime
              pattern: '{{.monthName}}\s{{.monthDay}}\s{{.year}}\s{{.time}}'
            - fieldName: log.serverIp
              pattern: '{{.ipv4}}|{{.ipv6}}|{{.hostname}}(\s)?\:'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: raw
      # Adding control flag field (Used to know if the message don't contains the header INT.INT mx_type mx_group)
      - add:
          function: 'string'
          params:
            key: log.controlFlag
            value: 'Init'
      # Begin message parsing
      # First extract the generic message, then parse it
      - grok:
          patterns:
            - fieldName: log.controlFlag
              pattern: '{{.data}}(events|flows|urls|ids-alerts|security_event)'
            - fieldName: log.genericEvent
              pattern: '{{.greedy}}'
          source: log.msg
      # Parsing variant INT.INT mx_type mx_group
      # Parsing from controlFlag (Format: Date? IP PORT INT.INT mx_type mx_group)
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: '{{.data}}{{.time}}'
            - fieldName: local.ip
              pattern: '{{.ipv4}}|{{.ipv6}}|{{.hostname}}'
            - fieldName: local.port
              pattern: '{{.integer}}'
            - fieldName: log.msgEventTime
              pattern: '{{.integer}}\.{{.integer}}'
            - fieldName: log.merakiType
              pattern: '{{.data}}\s'
            - fieldName: log.merakiGroup
              pattern: '{{.greedy}}'
          source: log.controlFlag
          where:
            variables:
              - get: log.controlFlag
                as: flag
                ofType: string
            expression: flag!="Init"
      - grok:
          patterns:
            - fieldName: log.msgEventTime
              pattern: '{{.integer}}\.{{.integer}}'
            - fieldName: log.merakiType
              pattern: '{{.data}}\s'
            - fieldName: log.merakiGroup
              pattern: '{{.greedy}}'
          source: log.controlFlag
          where:
            variables:
              - get: log.controlFlag
                as: flag
                ofType: string
            expression: flag!="Init"
      # ........................................
      # event vpn connectivity change
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: 'type(\s)?='
            - fieldName: action
              pattern: '{{.data}}\s'
            - fieldName: log.irrelevant
              pattern: 'vpn_type(\s)?='
            - fieldName: log.vpnType
              pattern: '''{{.data}}'''
            - fieldName: log.irrelevant
              pattern: 'peer_contact(\s)?='
            - fieldName: from.ip
              pattern: '''{{.data}}\:'
            - fieldName: from.port
              pattern: '{{.integer}}'''
            - fieldName: log.irrelevant
              pattern: 'peer_ident(\s)?='
            - fieldName: log.peerIdent
              pattern: '''{{.data}}'''
            - fieldName: log.irrelevant
              pattern: 'connectivity(\s)?='
            - fieldName: log.connectivity
              pattern: '{{.greedy}}'
          source: log.genericEvent
          where:
            variables:
              - get: log.controlFlag
                as: flag
                ofType: string
            expression: flag!="Init"
      
      # Cleaning fields
      - trim:
          function: suffix
          substring: ':'
          fields:
            - local.ip
            - from.ip
            - log.serverIp
      - trim:
          function: prefix
          substring: ''''
          fields:
            - from.ip
            - log.peerIdent
            - log.connectivity
            - log.vpnType
      - trim:
          function: suffix
          substring: ''''
          fields:
            - from.port
            - log.peerIdent
            - log.connectivity
            - log.vpnType
      #......................................................................#
      # Removing unused fields
      - delete:
          fields:
            - log.controlFlag
            - log.irrelevant
            - log.genericEvent
