export enum MetricAggregationEnum {
  AVERAGE = 'AVERAGE',
  COUNT = 'COUNT',
  MAX = 'MAX',
  MEDIAN = 'MEDIAN',
  MIN = 'MIN',
  PERCENTILE_RANK = 'PERCENTILE_RANK',
  PERCENTILE = 'PERCENTILE',
  SUM = 'SUM',
  TOP_HIT = 'TOP_HIT',
  UNIQUE_COUNT = 'UNIQUE_COUNT',
  AVERAGE_BUCKET = 'AVERAGE_BUCKET',
  MAX_BUCKET = 'MAX_BUCKET',
  MIN_BUCKET = 'MIN_BUCKET',
  SUM_BUCKET = 'SUM_BUCKET'
}
