-- Recreate the legacy JHipster persistent-audit schema (rollback only).

CREATE SEQUENCE IF NOT EXISTS jhi_persistent_audit_event_event_id_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS jhi_persistent_audit_event
(
    event_id   bigint DEFAULT nextval('jhi_persistent_audit_event_event_id_seq'::regclass) NOT NULL,
    principal  character varying(50) NOT NULL,
    event_date timestamp without time zone,
    event_type character varying(255),
    CONSTRAINT pk_jhi_persistent_audit_event PRIMARY KEY (event_id)
);
CREATE INDEX IF NOT EXISTS idx_persistent_audit_event ON jhi_persistent_audit_event USING btree (principal, event_date);

CREATE TABLE IF NOT EXISTS jhi_persistent_audit_evt_data
(
    event_id bigint                 NOT NULL,
    name     character varying(150) NOT NULL,
    value    character varying(255),
    CONSTRAINT jhi_persistent_audit_evt_data_pkey PRIMARY KEY (event_id, name),
    CONSTRAINT fk_evt_pers_audit_evt_data FOREIGN KEY (event_id) REFERENCES jhi_persistent_audit_event (event_id)
);
CREATE INDEX IF NOT EXISTS idx_persistent_audit_evt_data ON jhi_persistent_audit_evt_data USING btree (event_id);

ALTER TABLE jhi_user ADD COLUMN IF NOT EXISTS openvas_user_uuid character varying(50);
ALTER TABLE jhi_user ADD COLUMN IF NOT EXISTS openvas_user_id bigint;

-- Recreate the config-parameter section grouping (rollback only; the original
-- section rows and per-parameter assignments are not restored).
CREATE TABLE IF NOT EXISTS utm_configuration_section
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section        character varying(255),
    description    character varying(255),
    short_name     character varying(255),
    section_active boolean
);
ALTER TABLE utm_configuration_parameter ADD COLUMN IF NOT EXISTS section_id bigint;

-- Recreate the SOAR rule config-change history (rollback only; the original
-- snapshots are not restored).
CREATE TABLE IF NOT EXISTS utm_alert_response_rule_history
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id        bigint NOT NULL,
    created_date   timestamp without time zone NOT NULL,
    previous_state text   NOT NULL
);

-- Recreate the alerts checkpoint table (rollback only; the checkpoint value is
-- not restored — the scheduler never read it anyway).
CREATE TABLE IF NOT EXISTS utm_alert_last
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_alert_timestamp timestamp without time zone
);

-- Recreate the alert change-history table (rollback only; embedded OpenSearch
-- history is not migrated back).
CREATE TABLE IF NOT EXISTS utm_alert_log
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id      character varying(100) NOT NULL,
    log_user      character varying(50)  NOT NULL,
    log_date      timestamp without time zone NOT NULL,
    log_action    character varying(50)  NOT NULL,
    log_old_value text,
    log_new_value text,
    log_message   text
);
CREATE INDEX IF NOT EXISTS idx_utm_alert_log_alert_id ON utm_alert_log USING btree (alert_id);

-- IAM seed cleanup (leaves the legacy jhi_authority/jhi_user_authority alone).
DELETE FROM authority_permissions WHERE authority_name IN ('ROLE_ADMIN', 'ROLE_USER');
DELETE FROM permissions WHERE name IN ('users.read','users.write','users.delete','roles.read','roles.write','roles.delete','audit.read','soar.read','soar.write');
