-- Recreate the legacy JHipster persistent-audit schema (rollback only).

CREATE SEQUENCE IF NOT EXISTS jhi_persistent_audit_event_event_id_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS jhi_persistent_audit_event
(
    event_id   bigint DEFAULT nextval('jhi_persistent_audit_event_event_id_seq'::regclass) NOT NULL,
    principal  character varying(50) NOT NULL,
    event_date timestamp without time zone,
    event_type character varying(255),
    CONSTRAINT pk_jhi_persistent_audit_event PRIMARY KEY (event_id)
);
CREATE INDEX IF NOT EXISTS idx_persistent_audit_event ON jhi_persistent_audit_event USING btree (principal, event_date);

CREATE TABLE IF NOT EXISTS jhi_persistent_audit_evt_data
(
    event_id bigint                 NOT NULL,
    name     character varying(150) NOT NULL,
    value    character varying(255),
    CONSTRAINT jhi_persistent_audit_evt_data_pkey PRIMARY KEY (event_id, name),
    CONSTRAINT fk_evt_pers_audit_evt_data FOREIGN KEY (event_id) REFERENCES jhi_persistent_audit_event (event_id)
);
CREATE INDEX IF NOT EXISTS idx_persistent_audit_evt_data ON jhi_persistent_audit_evt_data USING btree (event_id);

ALTER TABLE jhi_user ADD COLUMN IF NOT EXISTS openvas_user_uuid character varying(50);
ALTER TABLE jhi_user ADD COLUMN IF NOT EXISTS openvas_user_id bigint;

-- Recreate the config-parameter section grouping (rollback only; the original
-- section rows and per-parameter assignments are not restored).
CREATE TABLE IF NOT EXISTS utm_configuration_section
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section        character varying(255),
    description    character varying(255),
    short_name     character varying(255),
    section_active boolean
);
ALTER TABLE utm_configuration_parameter ADD COLUMN IF NOT EXISTS section_id bigint;

-- Recreate the SOAR rule config-change history (rollback only; the original
-- snapshots are not restored).
CREATE TABLE IF NOT EXISTS utm_alert_response_rule_history
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id        bigint NOT NULL,
    created_date   timestamp without time zone NOT NULL,
    previous_state text   NOT NULL
);

-- Recreate the alerts checkpoint table (rollback only; the checkpoint value is
-- not restored — the scheduler never read it anyway).
CREATE TABLE IF NOT EXISTS utm_alert_last
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_alert_timestamp timestamp without time zone
);

-- Recreate the alert change-history table (rollback only; embedded OpenSearch
-- history is not migrated back).
CREATE TABLE IF NOT EXISTS utm_alert_log
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id      character varying(100) NOT NULL,
    log_user      character varying(50)  NOT NULL,
    log_date      timestamp without time zone NOT NULL,
    log_action    character varying(50)  NOT NULL,
    log_old_value text,
    log_new_value text,
    log_message   text
);
CREATE INDEX IF NOT EXISTS idx_utm_alert_log_alert_id ON utm_alert_log USING btree (alert_id);

-- Recreate the asset-metrics table (rollback only; the original rows are not
-- restored). Mirrors the former GORM-managed schema of domain.UtmAssetMetric.
CREATE TABLE IF NOT EXISTS utm_asset_metrics
(
    id         character varying NOT NULL PRIMARY KEY,
    asset_name character varying NOT NULL,
    metric     character varying NOT NULL,
    amount     bigint            NOT NULL,
    CONSTRAINT uq_asset_metric UNIQUE (asset_name, metric)
);

-- Recreate the agent-manager registry table (rollback only; mirrors the legacy
-- utm_agent_manager schema). The original rows are not restored.
CREATE TABLE IF NOT EXISTS utm_agent_manager
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_host    character varying(100) NOT NULL,
    manager_version character varying(50)  NOT NULL,
    manager_port    integer                NOT NULL,
    CONSTRAINT ux_utm_agent_manager_manager_host UNIQUE (manager_host)
);

-- Recreate the SOC AI processing-request table (rollback only; mirrors the legacy
-- utm_alert_socai_processing_request schema). The original rows are not restored.
CREATE TABLE IF NOT EXISTS utm_alert_socai_processing_request
(
    alert_id character varying(255) NOT NULL,
    CONSTRAINT utm_alert_socai_processing_request_pkey PRIMARY KEY (alert_id)
);

-- Recreate the licensing/client table (rollback only; mirrors the schema the
-- installer used to create). The seeded row and license values are not restored.
CREATE TABLE IF NOT EXISTS utm_client
(
    id                      serial NOT NULL,
    client_name             character varying(100),
    client_domain           character varying(100),
    client_prefix           character varying(10),
    client_mail             character varying(100),
    client_user             character varying(50),
    client_pass             character varying(50),
    client_licence_creation timestamp(0) without time zone,
    client_licence_expire   timestamp(0) without time zone,
    client_licence_id       character varying(100),
    client_licence_verified boolean NOT NULL,
    CONSTRAINT utm_client_pkey PRIMARY KEY (id)
);

-- Recreate the incident-response action/command/job/variable tables (rollback
-- only; mirrors the former GORM-managed schema). The seeded predefined actions
-- and any rows are not restored.
CREATE TABLE IF NOT EXISTS utm_incident_actions
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_command     character varying(255),
    action_description character varying(255),
    action_params      character varying(255),
    action_type        integer,
    action_editable    boolean NOT NULL DEFAULT FALSE,
    created_date       timestamp with time zone NOT NULL DEFAULT NOW(),
    modified_date      timestamp with time zone,
    created_user       character varying(50) NOT NULL DEFAULT 'system',
    modified_user      character varying(50)
);

CREATE TABLE IF NOT EXISTS utm_incident_action_command
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id   bigint NOT NULL,
    os_platform character varying(50),
    command     character varying(1024)
);

CREATE TABLE IF NOT EXISTS utm_incident_jobs
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id     bigint,
    params        character varying(1024),
    agent         character varying(255),
    status        integer,
    job_result    text,
    origin_id     integer NOT NULL DEFAULT 0,
    origin_type   character varying(50) NOT NULL DEFAULT '',
    created_date  timestamp with time zone NOT NULL DEFAULT NOW(),
    modified_date timestamp with time zone,
    created_user  character varying(50) NOT NULL DEFAULT 'system',
    modified_user character varying(50)
);

CREATE TABLE IF NOT EXISTS utm_incident_variables
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variable_name        character varying,
    variable_value       text,
    variable_description text,
    is_secret            boolean NOT NULL DEFAULT FALSE,
    created_by           character varying(255),
    last_modified_date   timestamp with time zone,
    last_modified_by     character varying(255),
    CONSTRAINT uq_utm_incident_variables_name UNIQUE (variable_name)
);

-- IAM seed cleanup (leaves the legacy jhi_authority/jhi_user_authority alone).
DELETE FROM authority_permissions WHERE authority_name IN ('ROLE_ADMIN', 'ROLE_USER');
DELETE FROM permissions WHERE name IN ('users.read','users.write','users.delete','roles.read','roles.write','roles.delete','config.read','config.write','audit.read','soar.read','soar.write','alerts.read','alerts.write');

-- Remove the seeded system-owned "False positive" alert tag.
DELETE FROM utm_alert_tag WHERE tag_name = 'False positive' AND system_owner = true;

-- Remove the seeded default mail configuration rows.
DELETE FROM utm_configuration_parameter WHERE conf_param_short IN (
    'utmstack.mail.host', 'utmstack.mail.port', 'utmstack.mail.username',
    'utmstack.mail.password', 'utmstack.mail.organization',
    'utmstack.mail.properties.mail.smtp.auth', 'utmstack.mail.from',
    'utmstack.mail.baseUrl'
);
