---
name: "🐞 Bug Report"
description: "Report a bug"
title: "(short issue description)"
labels: [bug, needs-triage]
assignees: []
body:
  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched (https://github.com/utmstack/UTMStack/issues) for past instances of this issue
          required: true
        - label: I have verified that my UTMStack version is up-to-date
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression Issue
      description: What is a regression? If it worked in a previous version but doesn't in the latest version, it's considered a
        regression. In this case, please provide specific version number in the report.
      options:
        - label: Select this option if this issue appears to be a regression.
          required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true   
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?

        Please include full errors, uncaught exceptions, stack traces, and relevant logs.
        If service responses are relevant, please include wire logs.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide concise steps that can be used to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false    
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false
  - type: input
    id: utmstack-version
    attributes:
      label: UTMStack Version
      description: |
        Please provide your current UTMStack version.
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
    validations:
      required: true
  - type: input
    id: hypervisor
    attributes:
      label: Hypervisor and Version | Server Vendor and Model
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser and version
    validations:
      required: true
