package schema

type AlertGPTDetails struct {
	AlertID                        string `json:"alert_id,omitempty"`
	Severity                       int    `json:"severity,omitempty"`
	TagRulesApplied                []int  `json:"tag_rules_applied,omitempty"`
	SeverityLabel                  string `json:"severity_label,omitempty"`
	Notes                          string `json:"notes,omitempty"`
	DataType                       string `json:"data_type,omitempty"`
	Description                    string `json:"description,omitempty"`
	StatusLabel                    string `json:"status_label,omitempty"`
	Tactic                         string `json:"tactic,omitempty"`
	Tags                           string `json:"tags,omitempty"`
	Reference                      string `json:"reference,omitempty"`
	Protocol                       string `json:"protocol,omitempty"`
	Timestamp                      string `json:"timestamp,omitempty"`
	Solution                       string `json:"solution,omitempty"`
	StatusObservation              string `json:"status_observation,omitempty"`
	Name                           string `json:"name,omitempty"`
	IsIncident                     bool   `json:"is_incident,omitempty"`
	Category                       string `json:"category,omitempty"`
	DataSource                     string `json:"data_source,omitempty"`
	Logs                           string `json:"logs,omitempty"`
	Status                         int    `json:"status,omitempty"`
	DestinationCountry             string `json:"destination_country,omitempty"`
	DestinationAccuracyRadius      int    `json:"destination_accuracy_radius,omitempty"`
	DestinationCity                string `json:"destination_city,omitempty"`
	DestinationIP                  string `json:"-"`
	DestinationPort                int    `json:"destination_port,omitempty"`
	DestinationCountryCode         string `json:"destination_country_code,omitempty"`
	DestinationIsAnonymousProxy    bool   `json:"destination_is_anonymous_proxy,omitempty"`
	DestinationHost                string `json:"destination_host,omitempty"`
	DestinationCoordinates         string `json:"destination_coordinates,omitempty"`
	DestinationIsSatelliteProvider bool   `json:"destination_is_satellite_provider,omitempty"`
	DestinationAso                 string `json:"destination_aso,omitempty"`
	DestinationAsn                 int    `json:"destination_asn,omitempty"`
	DestinationUser                string `json:"-"`
	SourceCountry                  string `json:"source_country,omitempty"`
	SourceAccuracyRadius           int    `json:"source_accuracy_radius,omitempty"`
	SourceCity                     string `json:"source_city,omitempty"`
	SourceIP                       string `json:"-"`
	SourceCoordinates              string `json:"source_coordinates,omitempty"`
	SourcePort                     int    `json:"source_port,omitempty"`
	SourceCountryCode              string `json:"source_country_code,omitempty"`
	SourceIsAnonymousProxy         bool   `json:"source_is_anonymous_proxy,omitempty"`
	SourceIsSatelliteProvider      bool   `json:"source_is_satellite_provider,omitempty"`
	SourceHost                     string `json:"source_host,omitempty"`
	SourceAso                      string `json:"source_aso,omitempty"`
	SourceAsn                      int    `json:"source_asn,omitempty"`
	SourceUser                     string `json:"-"`
	IncidentCreatedBy              string `json:"incident_created_by,omitempty"`
	IncidentObservation            string `json:"incident_observation,omitempty"`
	IncidentSource                 string `json:"incident_source,omitempty"`
	IncidentCreationDate           string `json:"incident_creation_date,omitempty"`
	IncidentName                   string `json:"incident_name,omitempty"`
	IncidentID                     string `json:"incident_id,omitempty"`
	GPTTimestamp                   string `json:"gpt_timestamp,omitempty"`
	GPTClassification              string `json:"gpt_classification,omitempty"`
	GPTReasoning                   string `json:"gpt_reasoning,omitempty"`
	GPTNextSteps                   string `json:"gpt_next_steps,omitempty"`
}
