export enum ReportShortNameEnum {
  RISK = 'RISK',
  IDENTITY = 'IDENTITY',
  VULNERABILITY = 'VULNERABILITY',
  FILE_TRACKING = 'FILE_TRACKING',
  ASSET = 'ASSET',
  THREAT_ACTIVITY_INCIDENT = 'THREAT_ACTIVITY_INCIDENT',
  THREAT_ACTIVITY_ALERT = 'THREAT_ACTIVITY_ALERT',
  AD_USR_PWD_EXPIRED = 'AD_USR_PWD_EXPIRED'
}
