package com.park.utmstack.domain.application_events.enums;

public enum ApplicationEventType {
    AUTH_ATTEMPT,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    TFA_CODE_SENT,
    TFA_CODE_VERIFY_ATTEMPT,
    TFA_VERIFIED,
    AUTH_LOGOUT,
    CONFIG_CHANGED,
    USER_MANAGEMENT,
    ACCESS_DENIED,
    ALERT_UPDATE_ATTEMPT,
    ALERT_UPDATE_SUCCESS,
    ALERT_NOTE_UPDATE_ATTEMPT,
    ALERT_NOTE_UPDATE_SUCCESS,
    ALERT_TAG_UPDATE_ATTEMPT,
    ALERT_CONVERT_TO_INCIDENT_ATTEMPT,
    ALERT_CONVERT_TO_INCIDENT_SUCCESS,
    ALERT_TAG_UPDATE_SUCCESS,
    ERROR,
    WARNING,
    INFO,
    UNDEFINED
}
