export enum BucketAggregationEnum {
  DATE_HISTOGRAM = 'DATE_HISTOGRAM',
  DATE_RANGE = 'DATE_RANGE',
  FILTERS = 'FILTERS',
  HISTOGRAM = 'HISTOGRAM',
  IPV4_RANGE = 'IPV4_RANGE',
  RANGE = 'RANGE',
  SIGNIFICANT_TERMS = 'SIGNIFICANT_TERMNS',
  TERMS = 'TERMS'
}
