package com.park.utmstack.domain.incident.enums;

/**
 * The IncidentHistoryActionEnum enumeration.
 */
public enum IncidentHistoryActionEnum {
    INCIDENT_CREATED,
    INCIDENT_MERGED,
    INCIDENT_COMPLETED,
    INCIDENT_ALERT_ADD,
    INCIDENT_ALERT_DELETED,
    INCIDENT_ALERT_STATUS_CHANGED,
    INCIDENT_ALERT_MOVED,
    INCIDENT_ASSIGNED_TO,
    INCIDENT_ASSIGNED_CHANGE,
    INCIDENT_STATUS_CHANGE,
    INCIDENT_NOTE_ADD,
    INCIDENT_NOTE_CHANGE,
    INCIDENT_COMMAND_EXECUTED
}
