export enum AssetFieldFilterEnum {
  IP = 'IP',
  MAC = 'MAC',
  NAME = 'IP',
  OS = 'OS',
  PROBE = 'PROBE',
  STATUS = 'STATUS',
  TYPE = 'TYPE',
  SEVERITY = 'SEVERITY',
  PORTS = 'PORTS',
  ALIVE = 'ALIVE',
  GROUP = 'GROUP',
  ALIAS = 'ALIAS',
  DATA_TYPES = 'DATA_TYPES',
}
