export enum AssetFieldEnum {
  ASSET_ID = 'id',
  ASSET_IP = 'assetIp',
  ASSET_NAME = 'assetName',
  ASSET_MAC = 'assetMac',
  ASSET_OS = 'assetOs',
  ASSET_ALIAS = 'assetAlias',
  ASSET_ADDRESSES = 'assetAddresses',
  ASSET_ALIASSESS = 'assetAliases',
  ASSET_PORTS = 'ports',
  ASSET_METRICS = 'metrics',
  ASSET_SOFTWARES = 'softwares',
  ASSET_IS_ALIVE = 'assetAlive',
  ASSET_SEVERITY = 'assetSeverity',
  ASSET_STATUS = 'assetStatus',
  ASSET_TYPE = 'assetType',
  ASSET_DISCOVERED = 'discoveredAt',
  ASSET_PROBE = 'serverName',
  ASSET_REGISTER_MODE = 'registeredMode'
}
