export const SUMMARY_COLUMNS = [
  { key: { field: 'dataType' }, title: 'Data Type' },
  { key: { field: 'dataSource' }, title: 'Data Source' },
  { key: { field: 'protocol' }, title: 'Protocol' },
  { key: { field: 'connectionStatus' }, title: 'Connection Status' },
  { key: { field: 'statusCode' }, title: 'Status Code' },
  { key: { field: 'actionResult' }, title: 'Action Result' },
  { key: { field: 'command' }, title: 'Command' },
  { key: { field: 'severity' }, title: 'Severity' },

  { key: { field: 'origin.host' }, title: 'Origin Host' },
  { key: { field: 'origin.ip' }, title: 'Origin IP' },
  { key: { field: 'origin.user' }, title: 'Origin User' },
  { key: { field: 'origin.group' }, title: 'Origin Group' },
  { key: { field: 'origin.port' }, title: 'Origin Port' },
  { key: { field: 'origin.domain' }, title: 'Origin Domain' },
  { key: { field: 'origin.fqdn' }, title: 'Origin FQDN' },
  { key: { field: 'origin.mac' }, title: 'Origin MAC' },
  { key: { field: 'origin.process' }, title: 'Origin Process' },
  { key: { field: 'origin.file' }, title: 'Origin File' },
  { key: { field: 'origin.path' }, title: 'Origin Path' },
  { key: { field: 'origin.hash' }, title: 'Origin Hash' },
  { key: { field: 'origin.url' }, title: 'Origin URL' },
  { key: { field: 'origin.email' }, title: 'Origin Email' },
  { key: { field: 'origin.bytesSent' }, title: 'Origin Bytes Sent' },
  { key: { field: 'origin.bytesReceived' }, title: 'Origin Bytes Received' },
  { key: { field: 'origin.packagesSent' }, title: 'Origin Packages Sent' },
  { key: { field: 'origin.packagesReceived' }, title: 'Origin Packages Received' },
  { key: { field: 'origin.connections' }, title: 'Origin Connections' },
  { key: { field: 'origin.usedCpuPercent' }, title: 'Origin Used CPU %' },
  { key: { field: 'origin.usedMemPercent' }, title: 'Origin Used Memory %' },
  { key: { field: 'origin.totalCpuUnits' }, title: 'Origin Total CPU Units' },
  { key: { field: 'origin.totalMem' }, title: 'Origin Total Memory' },
  { key: { field: 'origin.geolocation.country' }, title: 'Origin Geo Country' },
  { key: { field: 'origin.geolocation.city' }, title: 'Origin Geo City' },
  { key: { field: 'origin.geolocation.latitude' }, title: 'Origin Geo Latitude' },
  { key: { field: 'origin.geolocation.longitude' }, title: 'Origin Geo Longitude' },
  { key: { field: 'origin.geolocation.asn' }, title: 'Origin Geo ASN' },
  { key: { field: 'origin.geolocation.aso' }, title: 'Origin Geo ASO' },
  { key: { field: 'origin.geolocation.countryCode' }, title: 'Origin Geo Country Code' },
  { key: { field: 'origin.geolocation.accuracy' }, title: 'Origin Geo Accuracy' },

  { key: { field: 'target.host' }, title: 'Target Host' },
  { key: { field: 'target.ip' }, title: 'Target IP' },
  { key: { field: 'target.user' }, title: 'Target User' },
  { key: { field: 'target.group' }, title: 'Target Group' },
  { key: { field: 'target.port' }, title: 'Target Port' },
  { key: { field: 'target.domain' }, title: 'Target Domain' },
  { key: { field: 'target.fqdn' }, title: 'Target FQDN' },
  { key: { field: 'target.mac' }, title: 'Target MAC' },
  { key: { field: 'target.process' }, title: 'Target Process' },
  { key: { field: 'target.file' }, title: 'Target File' },
  { key: { field: 'target.path' }, title: 'Target Path' },
  { key: { field: 'target.hash' }, title: 'Target Hash' },
  { key: { field: 'target.url' }, title: 'Target URL' },
  { key: { field: 'target.email' }, title: 'Target Email' },
  { key: { field: 'target.bytesSent' }, title: 'Target Bytes Sent' },
  { key: { field: 'target.bytesReceived' }, title: 'Target Bytes Received' },
  { key: { field: 'target.packagesSent' }, title: 'Target Packages Sent' },
  { key: { field: 'target.packagesReceived' }, title: 'Target Packages Received' },
  { key: { field: 'target.connections' }, title: 'Target Connections' },
  { key: { field: 'target.usedCpuPercent' }, title: 'Target Used CPU %' },
  { key: { field: 'target.usedMemPercent' }, title: 'Target Used Memory %' },
  { key: { field: 'target.totalCpuUnits' }, title: 'Target Total CPU Units' },
  { key: { field: 'target.totalMem' }, title: 'Target Total Memory' },
  { key: { field: 'target.geolocation.country' }, title: 'Target Geo Country' },
  { key: { field: 'target.geolocation.city' }, title: 'Target Geo City' },
  { key: { field: 'target.geolocation.latitude' }, title: 'Target Geo Latitude' },
  { key: { field: 'target.geolocation.longitude' }, title: 'Target Geo Longitude' },
  { key: { field: 'target.geolocation.asn' }, title: 'Target Geo ASN' },
  { key: { field: 'target.geolocation.aso' }, title: 'Target Geo ASO' },
  { key: { field: 'target.geolocation.countryCode' }, title: 'Target Geo Country Code' },
  { key: { field: 'target.geolocation.accuracy' }, title: 'Target Geo Accuracy' },
];

