// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: collector.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorServiceClient interface {
	RegisterCollector(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	DeleteCollector(ctx context.Context, in *CollectorDelete, opts ...grpc.CallOption) (*CollectorResponse, error)
	ListCollector(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCollectorResponse, error)
	CollectorStream(ctx context.Context, opts ...grpc.CallOption) (CollectorService_CollectorStreamClient, error)
	ListCollectorHostnames(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CollectorHostnames, error)
	GetCollectorsByHostnameAndModule(ctx context.Context, in *FilterByHostAndModule, opts ...grpc.CallOption) (*ListCollectorResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) RegisterCollector(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/agent.CollectorService/RegisterCollector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) DeleteCollector(ctx context.Context, in *CollectorDelete, opts ...grpc.CallOption) (*CollectorResponse, error) {
	out := new(CollectorResponse)
	err := c.cc.Invoke(ctx, "/agent.CollectorService/DeleteCollector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) ListCollector(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCollectorResponse, error) {
	out := new(ListCollectorResponse)
	err := c.cc.Invoke(ctx, "/agent.CollectorService/ListCollector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) CollectorStream(ctx context.Context, opts ...grpc.CallOption) (CollectorService_CollectorStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], "/agent.CollectorService/CollectorStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceCollectorStreamClient{stream}
	return x, nil
}

type CollectorService_CollectorStreamClient interface {
	Send(*CollectorMessages) error
	Recv() (*CollectorMessages, error)
	grpc.ClientStream
}

type collectorServiceCollectorStreamClient struct {
	grpc.ClientStream
}

func (x *collectorServiceCollectorStreamClient) Send(m *CollectorMessages) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectorServiceCollectorStreamClient) Recv() (*CollectorMessages, error) {
	m := new(CollectorMessages)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorServiceClient) ListCollectorHostnames(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CollectorHostnames, error) {
	out := new(CollectorHostnames)
	err := c.cc.Invoke(ctx, "/agent.CollectorService/ListCollectorHostnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) GetCollectorsByHostnameAndModule(ctx context.Context, in *FilterByHostAndModule, opts ...grpc.CallOption) (*ListCollectorResponse, error) {
	out := new(ListCollectorResponse)
	err := c.cc.Invoke(ctx, "/agent.CollectorService/GetCollectorsByHostnameAndModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility
type CollectorServiceServer interface {
	RegisterCollector(context.Context, *RegisterRequest) (*AuthResponse, error)
	DeleteCollector(context.Context, *CollectorDelete) (*CollectorResponse, error)
	ListCollector(context.Context, *ListRequest) (*ListCollectorResponse, error)
	CollectorStream(CollectorService_CollectorStreamServer) error
	ListCollectorHostnames(context.Context, *ListRequest) (*CollectorHostnames, error)
	GetCollectorsByHostnameAndModule(context.Context, *FilterByHostAndModule) (*ListCollectorResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorServiceServer struct {
}

func (UnimplementedCollectorServiceServer) RegisterCollector(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCollector not implemented")
}
func (UnimplementedCollectorServiceServer) DeleteCollector(context.Context, *CollectorDelete) (*CollectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollector not implemented")
}
func (UnimplementedCollectorServiceServer) ListCollector(context.Context, *ListRequest) (*ListCollectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollector not implemented")
}
func (UnimplementedCollectorServiceServer) CollectorStream(CollectorService_CollectorStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CollectorStream not implemented")
}
func (UnimplementedCollectorServiceServer) ListCollectorHostnames(context.Context, *ListRequest) (*CollectorHostnames, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollectorHostnames not implemented")
}
func (UnimplementedCollectorServiceServer) GetCollectorsByHostnameAndModule(context.Context, *FilterByHostAndModule) (*ListCollectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectorsByHostnameAndModule not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_RegisterCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).RegisterCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CollectorService/RegisterCollector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).RegisterCollector(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_DeleteCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectorDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).DeleteCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CollectorService/DeleteCollector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).DeleteCollector(ctx, req.(*CollectorDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_ListCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ListCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CollectorService/ListCollector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ListCollector(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_CollectorStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).CollectorStream(&collectorServiceCollectorStreamServer{stream})
}

type CollectorService_CollectorStreamServer interface {
	Send(*CollectorMessages) error
	Recv() (*CollectorMessages, error)
	grpc.ServerStream
}

type collectorServiceCollectorStreamServer struct {
	grpc.ServerStream
}

func (x *collectorServiceCollectorStreamServer) Send(m *CollectorMessages) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectorServiceCollectorStreamServer) Recv() (*CollectorMessages, error) {
	m := new(CollectorMessages)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CollectorService_ListCollectorHostnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ListCollectorHostnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CollectorService/ListCollectorHostnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ListCollectorHostnames(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_GetCollectorsByHostnameAndModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterByHostAndModule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).GetCollectorsByHostnameAndModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CollectorService/GetCollectorsByHostnameAndModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).GetCollectorsByHostnameAndModule(ctx, req.(*FilterByHostAndModule))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCollector",
			Handler:    _CollectorService_RegisterCollector_Handler,
		},
		{
			MethodName: "DeleteCollector",
			Handler:    _CollectorService_DeleteCollector_Handler,
		},
		{
			MethodName: "ListCollector",
			Handler:    _CollectorService_ListCollector_Handler,
		},
		{
			MethodName: "ListCollectorHostnames",
			Handler:    _CollectorService_ListCollectorHostnames_Handler,
		},
		{
			MethodName: "GetCollectorsByHostnameAndModule",
			Handler:    _CollectorService_GetCollectorsByHostnameAndModule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectorStream",
			Handler:       _CollectorService_CollectorStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "collector.proto",
}

// CollectorConfigurationServiceClient is the client API for CollectorConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorConfigurationServiceClient interface {
	CollectorConfigStream(ctx context.Context, opts ...grpc.CallOption) (CollectorConfigurationService_CollectorConfigStreamClient, error)
}

type collectorConfigurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorConfigurationServiceClient(cc grpc.ClientConnInterface) CollectorConfigurationServiceClient {
	return &collectorConfigurationServiceClient{cc}
}

func (c *collectorConfigurationServiceClient) CollectorConfigStream(ctx context.Context, opts ...grpc.CallOption) (CollectorConfigurationService_CollectorConfigStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorConfigurationService_ServiceDesc.Streams[0], "/agent.CollectorConfigurationService/CollectorConfigStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorConfigurationServiceCollectorConfigStreamClient{stream}
	return x, nil
}

type CollectorConfigurationService_CollectorConfigStreamClient interface {
	Send(*CollectorConfig) error
	Recv() (*ConfigKnowledge, error)
	grpc.ClientStream
}

type collectorConfigurationServiceCollectorConfigStreamClient struct {
	grpc.ClientStream
}

func (x *collectorConfigurationServiceCollectorConfigStreamClient) Send(m *CollectorConfig) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectorConfigurationServiceCollectorConfigStreamClient) Recv() (*ConfigKnowledge, error) {
	m := new(ConfigKnowledge)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorConfigurationServiceServer is the server API for CollectorConfigurationService service.
// All implementations must embed UnimplementedCollectorConfigurationServiceServer
// for forward compatibility
type CollectorConfigurationServiceServer interface {
	CollectorConfigStream(CollectorConfigurationService_CollectorConfigStreamServer) error
	mustEmbedUnimplementedCollectorConfigurationServiceServer()
}

// UnimplementedCollectorConfigurationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorConfigurationServiceServer struct {
}

func (UnimplementedCollectorConfigurationServiceServer) CollectorConfigStream(CollectorConfigurationService_CollectorConfigStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CollectorConfigStream not implemented")
}
func (UnimplementedCollectorConfigurationServiceServer) mustEmbedUnimplementedCollectorConfigurationServiceServer() {
}

// UnsafeCollectorConfigurationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorConfigurationServiceServer will
// result in compilation errors.
type UnsafeCollectorConfigurationServiceServer interface {
	mustEmbedUnimplementedCollectorConfigurationServiceServer()
}

func RegisterCollectorConfigurationServiceServer(s grpc.ServiceRegistrar, srv CollectorConfigurationServiceServer) {
	s.RegisterService(&CollectorConfigurationService_ServiceDesc, srv)
}

func _CollectorConfigurationService_CollectorConfigStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorConfigurationServiceServer).CollectorConfigStream(&collectorConfigurationServiceCollectorConfigStreamServer{stream})
}

type CollectorConfigurationService_CollectorConfigStreamServer interface {
	Send(*ConfigKnowledge) error
	Recv() (*CollectorConfig, error)
	grpc.ServerStream
}

type collectorConfigurationServiceCollectorConfigStreamServer struct {
	grpc.ServerStream
}

func (x *collectorConfigurationServiceCollectorConfigStreamServer) Send(m *ConfigKnowledge) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectorConfigurationServiceCollectorConfigStreamServer) Recv() (*CollectorConfig, error) {
	m := new(CollectorConfig)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorConfigurationService_ServiceDesc is the grpc.ServiceDesc for CollectorConfigurationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorConfigurationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.CollectorConfigurationService",
	HandlerType: (*CollectorConfigurationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectorConfigStream",
			Handler:       _CollectorConfigurationService_CollectorConfigStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "collector.proto",
}
