# Json filter, version 2.0
# Allow processing of any one line json 
pipeline:
  - dataTypes: [json-input]
    order: 19  # global pipeline order -- unique across all filters, customer-adjustable
    steps:
      - json:
          source: raw