export enum IncidentOriginTypeEnum {
  ALERT = 'ALERT',
  USER_EXECUTION = 'USER_EXECUTION',
  DATA_SOURCE = 'DATA_SOURCES',
  INCIDENT = 'INCIDENT',
  INCIDENT_RESPONSE = 'INCIDENT_RESPONSE',
  INCIDENT_RESPONSE_AUTOMATION = 'INCIDENT_RESPONSE_AUTOMATION'
}
