# Fortinet firewall module filter, version 3.0.0
# Based in docs and samples provided
# 
# Documentations
# 1- https://docs.fortinet.com/document/fortigate/7.0.4/fortios-log-message-reference/357866/log-message-fields 
# 2- https://docs.fortinet.com/document/fortigate/7.0.4/fortios-log-message-reference/656858/log-id-definitions 
# 
# Implementation
# 1. Parsing the RAW field containing the Fortinet firewall
pipeline:
  - dataTypes:
      - firewall-fortigate-traffic
    steps:

      #Using grok to parse priority if present
      - grok:
          patterns:
            - fieldName: log.priority
              pattern: '\<{{.data}}\>'
            - fieldName: log.kvMessage
              pattern: '{{.greedy}}'

      #Using the kv filter with default config, usefull in key-value logs
      - kv:
          source: log.kvMessage
          fieldSplit: " "
          valueSplit: "="

      # Remove fields that have issues with kv filter
      - delete:
          fields:
            - log.msg
      
      # Using grok to parse kv issued fields
      - grok:
          patterns:
            - fieldName: log.irrelevant
              pattern: '{{.data}}(msg=)'
            - fieldName: log.msg
              pattern: '{{.data}}({{.word}}=)'
            - fieldName: log.irrelevant
              pattern: '{{.greedy}}'
          source: log.kvMessage

      # Using grok to remove irrelevant data
      - grok:
          patterns:
            - fieldName: log.msg
              pattern: '{{.greedy}}{{.space}}'
            - fieldName: log.irrelevant
              pattern: '{{.word}}(=)'
          source: log.msg

      # Rename standard fields and fields out of kv result
      - rename:
          from:
            - log.action
          to: action
      - rename:
          from:
            - log.dstip
          to: target.ip
      - rename:
          from:
            - log.dstport
          to: target.port
      - rename:
          from:
            - log.srcip
          to: origin.ip
      - rename:
          from:
            - log.srcport
          to: origin.port

      - rename:
          from:
            - log.dest_ip
          to: target.ip
      - rename:
          from:
            - log.dest_port
          to: target.port
      - rename:
          from:
            - log.src_ip
          to: origin.ip
      - rename:
          from:
            - log.src_port
          to: origin.port

      # Removing unused caracters
      - trim:
          function: prefix
          substring: '<'
          fields:
            - log.priority
      - trim:
          function: suffix
          substring: '>'
          fields:
            - log.priority

      # Adding geolocation to origin.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: origin.ip
            destination: origin.geolocation
          where:
            variables:
              - get: origin.ip
                as: ip
                ofType: string
            expression: "ip_ok == true"
      
      # Adding geolocation to target.ip
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: target.ip
            destination: target.geolocation
          where:
            variables:
              - get: target.ip
                as: ip
                ofType: string
            expression: "ip_ok == true"

      # Removing unused fields
      - delete:
          fields:
            - log.kvMessage