# Azure Envent-Hub filter, version 2.0.0
# 
# Documentations
# 1- https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log
# 2- https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log-schema
pipeline:
  - dataTypes:
      - azure
    steps:
      - json:
          source: raw
    
      # .......................................................................#
      # Renaming fields
      # .......................................................................#
      - rename:
          from:
            - log.ResponseBodySize
          to: origin.bytesSent

      - rename:
          from:
            - log.ResponseHeaderSize
          to: origin.bytesReceived

      - rename:
          from:
            - log.Uri
          to: target.url

      - rename:
          from:
            - log.AccountName
          to: origin.host

      - rename:
          from:
            - log.StatusCode
          to: statusCode

      - rename:
          from:
            - log.Protocol
          to: protocol

      - rename:
          from:
            - log.StatusText
          to: connectionStatus

      - rename:
          from:
            - log.Location
          to: origin.geolocation.country
          

      # .......................................................................#
      # Using grok to parse IP and port of the CallerIpAddress
      # .......................................................................#
      - grok:
          patterns:
            - fieldName: origin.ip
              pattern: '{{.ipv4}}(:)'
            - fieldName: origin.port
              pattern: '{{.integer}}'
          source: log.CallerIpAddress
          where:
            variables:
              - get: log.CallerIpAddress
                as: ip
                ofType: string
            expression: ip.contains(":")

      # .......................................................................#
      # Remove caracters unnecessary to remote.ip
      # .......................................................................#
      - trim:
          function: suffix
          substring: ':'
          fields:
            - origin.ip

      # .......................................................................#
      # Add geolocation to remote.ip
      # .......................................................................#
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: origin.ip
            destination: origin.geolocation
          where:
            variables:
              - get: origin.ip
                as: ip
                ofType: string
            expression: "ip_ok == true"

      # .......................................................................#
      # Fields conversions
      # .......................................................................#
      - cast:
          fields:
            - origin.port
            - statusCode
          to: int

      - cast:
          fields:
            - origin.bytesSent
            - origin.bytesReceived
          to: float64