// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.park.utmstack.service.grpc;

/**
 * Protobuf service {@code agent.AgentTypeService}
 */
public  abstract class AgentTypeService
    implements com.google.protobuf.Service {
  protected AgentTypeService() {}

  public interface Interface {
    /**
     * <code>rpc ListAgentTypes(.agent.ListRequest) returns (.agent.ListAgentsTypeResponse);</code>
     */
    public abstract void listAgentTypes(
        com.google.protobuf.RpcController controller,
        com.park.utmstack.service.grpc.ListRequest request,
        com.google.protobuf.RpcCallback<com.park.utmstack.service.grpc.ListAgentsTypeResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new AgentTypeService() {
      @java.lang.Override
      public  void listAgentTypes(
          com.google.protobuf.RpcController controller,
          com.park.utmstack.service.grpc.ListRequest request,
          com.google.protobuf.RpcCallback<com.park.utmstack.service.grpc.ListAgentsTypeResponse> done) {
        impl.listAgentTypes(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.listAgentTypes(controller, (com.park.utmstack.service.grpc.ListRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.park.utmstack.service.grpc.ListRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.park.utmstack.service.grpc.ListAgentsTypeResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc ListAgentTypes(.agent.ListRequest) returns (.agent.ListAgentsTypeResponse);</code>
   */
  public abstract void listAgentTypes(
      com.google.protobuf.RpcController controller,
      com.park.utmstack.service.grpc.ListRequest request,
      com.google.protobuf.RpcCallback<com.park.utmstack.service.grpc.ListAgentsTypeResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.park.utmstack.service.grpc.AgentManagerGrpc.getDescriptor().getServices().get(3);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.listAgentTypes(controller, (com.park.utmstack.service.grpc.ListRequest)request,
          com.google.protobuf.RpcUtil.<com.park.utmstack.service.grpc.ListAgentsTypeResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.park.utmstack.service.grpc.ListRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.park.utmstack.service.grpc.ListAgentsTypeResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.park.utmstack.service.grpc.AgentTypeService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void listAgentTypes(
        com.google.protobuf.RpcController controller,
        com.park.utmstack.service.grpc.ListRequest request,
        com.google.protobuf.RpcCallback<com.park.utmstack.service.grpc.ListAgentsTypeResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.park.utmstack.service.grpc.ListAgentsTypeResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.park.utmstack.service.grpc.ListAgentsTypeResponse.class,
          com.park.utmstack.service.grpc.ListAgentsTypeResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.park.utmstack.service.grpc.ListAgentsTypeResponse listAgentTypes(
        com.google.protobuf.RpcController controller,
        com.park.utmstack.service.grpc.ListRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.park.utmstack.service.grpc.ListAgentsTypeResponse listAgentTypes(
        com.google.protobuf.RpcController controller,
        com.park.utmstack.service.grpc.ListRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.park.utmstack.service.grpc.ListAgentsTypeResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.park.utmstack.service.grpc.ListAgentsTypeResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:agent.AgentTypeService)
}

