// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.park.utmstack.service.grpc;

/**
 * Protobuf type {@code agent.Agent}
 */
public final class Agent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.Agent)
    AgentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Agent.newBuilder() to construct.
  private Agent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Agent() {
    ip_ = "";
    hostname_ = "";
    os_ = "";
    status_ = 0;
    platform_ = "";
    version_ = "";
    agentKey_ = "";
    lastSeen_ = "";
    mac_ = "";
    osMajorVersion_ = "";
    osMinorVersion_ = "";
    aliases_ = "";
    addresses_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Agent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.park.utmstack.service.grpc.AgentManagerGrpc.internal_static_agent_Agent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.park.utmstack.service.grpc.AgentManagerGrpc.internal_static_agent_Agent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.park.utmstack.service.grpc.Agent.class, com.park.utmstack.service.grpc.Agent.Builder.class);
  }

  public static final int IP_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ip_ = "";
  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  @java.lang.Override
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostname_ = "";
  /**
   * <code>string hostname = 2;</code>
   * @return The hostname.
   */
  @java.lang.Override
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }
  /**
   * <code>string hostname = 2;</code>
   * @return The bytes for hostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object os_ = "";
  /**
   * <code>string os = 3;</code>
   * @return The os.
   */
  @java.lang.Override
  public java.lang.String getOs() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      os_ = s;
      return s;
    }
  }
  /**
   * <code>string os = 3;</code>
   * @return The bytes for os.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsBytes() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      os_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_ = 0;
  /**
   * <code>.agent.AgentStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.agent.AgentStatus status = 4;</code>
   * @return The status.
   */
  @java.lang.Override public com.park.utmstack.service.grpc.AgentStatus getStatus() {
    com.park.utmstack.service.grpc.AgentStatus result = com.park.utmstack.service.grpc.AgentStatus.forNumber(status_);
    return result == null ? com.park.utmstack.service.grpc.AgentStatus.UNRECOGNIZED : result;
  }

  public static final int PLATFORM_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object platform_ = "";
  /**
   * <code>string platform = 5;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <code>string platform = 5;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 6;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 6;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENT_KEY_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentKey_ = "";
  /**
   * <code>string agent_key = 7;</code>
   * @return The agentKey.
   */
  @java.lang.Override
  public java.lang.String getAgentKey() {
    java.lang.Object ref = agentKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentKey_ = s;
      return s;
    }
  }
  /**
   * <code>string agent_key = 7;</code>
   * @return The bytes for agentKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentKeyBytes() {
    java.lang.Object ref = agentKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 8;
  private int id_ = 0;
  /**
   * <code>uint32 id = 8;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int LAST_SEEN_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastSeen_ = "";
  /**
   * <code>string last_seen = 9;</code>
   * @return The lastSeen.
   */
  @java.lang.Override
  public java.lang.String getLastSeen() {
    java.lang.Object ref = lastSeen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastSeen_ = s;
      return s;
    }
  }
  /**
   * <code>string last_seen = 9;</code>
   * @return The bytes for lastSeen.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastSeenBytes() {
    java.lang.Object ref = lastSeen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastSeen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAC_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mac_ = "";
  /**
   * <code>string mac = 10;</code>
   * @return The mac.
   */
  @java.lang.Override
  public java.lang.String getMac() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mac_ = s;
      return s;
    }
  }
  /**
   * <code>string mac = 10;</code>
   * @return The bytes for mac.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMacBytes() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_MAJOR_VERSION_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object osMajorVersion_ = "";
  /**
   * <code>string os_major_version = 11;</code>
   * @return The osMajorVersion.
   */
  @java.lang.Override
  public java.lang.String getOsMajorVersion() {
    java.lang.Object ref = osMajorVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osMajorVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string os_major_version = 11;</code>
   * @return The bytes for osMajorVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsMajorVersionBytes() {
    java.lang.Object ref = osMajorVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osMajorVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_MINOR_VERSION_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object osMinorVersion_ = "";
  /**
   * <code>string os_minor_version = 12;</code>
   * @return The osMinorVersion.
   */
  @java.lang.Override
  public java.lang.String getOsMinorVersion() {
    java.lang.Object ref = osMinorVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osMinorVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string os_minor_version = 12;</code>
   * @return The bytes for osMinorVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsMinorVersionBytes() {
    java.lang.Object ref = osMinorVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osMinorVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALIASES_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aliases_ = "";
  /**
   * <code>string aliases = 13;</code>
   * @return The aliases.
   */
  @java.lang.Override
  public java.lang.String getAliases() {
    java.lang.Object ref = aliases_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aliases_ = s;
      return s;
    }
  }
  /**
   * <code>string aliases = 13;</code>
   * @return The bytes for aliases.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasesBytes() {
    java.lang.Object ref = aliases_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aliases_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESSES_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object addresses_ = "";
  /**
   * <code>string addresses = 14;</code>
   * @return The addresses.
   */
  @java.lang.Override
  public java.lang.String getAddresses() {
    java.lang.Object ref = addresses_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addresses_ = s;
      return s;
    }
  }
  /**
   * <code>string addresses = 14;</code>
   * @return The bytes for addresses.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressesBytes() {
    java.lang.Object ref = addresses_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addresses_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, os_);
    }
    if (status_ != com.park.utmstack.service.grpc.AgentStatus.ONLINE.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agentKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, agentKey_);
    }
    if (id_ != 0) {
      output.writeUInt32(8, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSeen_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, lastSeen_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mac_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mac_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osMajorVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, osMajorVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osMinorVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, osMinorVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aliases_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, aliases_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addresses_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, addresses_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, os_);
    }
    if (status_ != com.park.utmstack.service.grpc.AgentStatus.ONLINE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agentKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, agentKey_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSeen_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, lastSeen_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mac_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mac_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osMajorVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, osMajorVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osMinorVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, osMinorVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aliases_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, aliases_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addresses_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, addresses_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.park.utmstack.service.grpc.Agent)) {
      return super.equals(obj);
    }
    com.park.utmstack.service.grpc.Agent other = (com.park.utmstack.service.grpc.Agent) obj;

    if (!getIp()
        .equals(other.getIp())) return false;
    if (!getHostname()
        .equals(other.getHostname())) return false;
    if (!getOs()
        .equals(other.getOs())) return false;
    if (status_ != other.status_) return false;
    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getAgentKey()
        .equals(other.getAgentKey())) return false;
    if (getId()
        != other.getId()) return false;
    if (!getLastSeen()
        .equals(other.getLastSeen())) return false;
    if (!getMac()
        .equals(other.getMac())) return false;
    if (!getOsMajorVersion()
        .equals(other.getOsMajorVersion())) return false;
    if (!getOsMinorVersion()
        .equals(other.getOsMinorVersion())) return false;
    if (!getAliases()
        .equals(other.getAliases())) return false;
    if (!getAddresses()
        .equals(other.getAddresses())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostname().hashCode();
    hash = (37 * hash) + OS_FIELD_NUMBER;
    hash = (53 * hash) + getOs().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + AGENT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAgentKey().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + LAST_SEEN_FIELD_NUMBER;
    hash = (53 * hash) + getLastSeen().hashCode();
    hash = (37 * hash) + MAC_FIELD_NUMBER;
    hash = (53 * hash) + getMac().hashCode();
    hash = (37 * hash) + OS_MAJOR_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsMajorVersion().hashCode();
    hash = (37 * hash) + OS_MINOR_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsMinorVersion().hashCode();
    hash = (37 * hash) + ALIASES_FIELD_NUMBER;
    hash = (53 * hash) + getAliases().hashCode();
    hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
    hash = (53 * hash) + getAddresses().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.park.utmstack.service.grpc.Agent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.park.utmstack.service.grpc.Agent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.park.utmstack.service.grpc.Agent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.park.utmstack.service.grpc.Agent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.park.utmstack.service.grpc.Agent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.Agent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.Agent)
      com.park.utmstack.service.grpc.AgentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.park.utmstack.service.grpc.AgentManagerGrpc.internal_static_agent_Agent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.park.utmstack.service.grpc.AgentManagerGrpc.internal_static_agent_Agent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.park.utmstack.service.grpc.Agent.class, com.park.utmstack.service.grpc.Agent.Builder.class);
    }

    // Construct using com.park.utmstack.service.grpc.Agent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ip_ = "";
      hostname_ = "";
      os_ = "";
      status_ = 0;
      platform_ = "";
      version_ = "";
      agentKey_ = "";
      id_ = 0;
      lastSeen_ = "";
      mac_ = "";
      osMajorVersion_ = "";
      osMinorVersion_ = "";
      aliases_ = "";
      addresses_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.park.utmstack.service.grpc.AgentManagerGrpc.internal_static_agent_Agent_descriptor;
    }

    @java.lang.Override
    public com.park.utmstack.service.grpc.Agent getDefaultInstanceForType() {
      return com.park.utmstack.service.grpc.Agent.getDefaultInstance();
    }

    @java.lang.Override
    public com.park.utmstack.service.grpc.Agent build() {
      com.park.utmstack.service.grpc.Agent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.park.utmstack.service.grpc.Agent buildPartial() {
      com.park.utmstack.service.grpc.Agent result = new com.park.utmstack.service.grpc.Agent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.park.utmstack.service.grpc.Agent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ip_ = ip_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hostname_ = hostname_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.os_ = os_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.platform_ = platform_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.agentKey_ = agentKey_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.lastSeen_ = lastSeen_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.mac_ = mac_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.osMajorVersion_ = osMajorVersion_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.osMinorVersion_ = osMinorVersion_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.aliases_ = aliases_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.addresses_ = addresses_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.park.utmstack.service.grpc.Agent) {
        return mergeFrom((com.park.utmstack.service.grpc.Agent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.park.utmstack.service.grpc.Agent other) {
      if (other == com.park.utmstack.service.grpc.Agent.getDefaultInstance()) return this;
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getOs().isEmpty()) {
        os_ = other.os_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getAgentKey().isEmpty()) {
        agentKey_ = other.agentKey_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getLastSeen().isEmpty()) {
        lastSeen_ = other.lastSeen_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getMac().isEmpty()) {
        mac_ = other.mac_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getOsMajorVersion().isEmpty()) {
        osMajorVersion_ = other.osMajorVersion_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getOsMinorVersion().isEmpty()) {
        osMinorVersion_ = other.osMinorVersion_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getAliases().isEmpty()) {
        aliases_ = other.aliases_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getAddresses().isEmpty()) {
        addresses_ = other.addresses_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ip_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              hostname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              os_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              platform_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              agentKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              lastSeen_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              mac_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              osMajorVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              osMinorVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              aliases_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              addresses_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 1;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 1;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 1;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      ip_ = getDefaultInstance().getIp();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 1;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object hostname_ = "";
    /**
     * <code>string hostname = 2;</code>
     * @return The hostname.
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostname = 2;</code>
     * @return The bytes for hostname.
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostname = 2;</code>
     * @param value The hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostname() {
      hostname_ = getDefaultInstance().getHostname();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 2;</code>
     * @param value The bytes for hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object os_ = "";
    /**
     * <code>string os = 3;</code>
     * @return The os.
     */
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os = 3;</code>
     * @return The bytes for os.
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os = 3;</code>
     * @param value The os to set.
     * @return This builder for chaining.
     */
    public Builder setOs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      os_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string os = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOs() {
      os_ = getDefaultInstance().getOs();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string os = 3;</code>
     * @param value The bytes for os to set.
     * @return This builder for chaining.
     */
    public Builder setOsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      os_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.agent.AgentStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.agent.AgentStatus status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.agent.AgentStatus status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.park.utmstack.service.grpc.AgentStatus getStatus() {
      com.park.utmstack.service.grpc.AgentStatus result = com.park.utmstack.service.grpc.AgentStatus.forNumber(status_);
      return result == null ? com.park.utmstack.service.grpc.AgentStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.agent.AgentStatus status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.park.utmstack.service.grpc.AgentStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.agent.AgentStatus status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object platform_ = "";
    /**
     * <code>string platform = 5;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform = 5;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform = 5;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      platform_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      platform_ = getDefaultInstance().getPlatform();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 5;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      platform_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 6;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object agentKey_ = "";
    /**
     * <code>string agent_key = 7;</code>
     * @return The agentKey.
     */
    public java.lang.String getAgentKey() {
      java.lang.Object ref = agentKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agent_key = 7;</code>
     * @return The bytes for agentKey.
     */
    public com.google.protobuf.ByteString
        getAgentKeyBytes() {
      java.lang.Object ref = agentKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agent_key = 7;</code>
     * @param value The agentKey to set.
     * @return This builder for chaining.
     */
    public Builder setAgentKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string agent_key = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentKey() {
      agentKey_ = getDefaultInstance().getAgentKey();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string agent_key = 7;</code>
     * @param value The bytes for agentKey to set.
     * @return This builder for chaining.
     */
    public Builder setAgentKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>uint32 id = 8;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 8;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000080);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lastSeen_ = "";
    /**
     * <code>string last_seen = 9;</code>
     * @return The lastSeen.
     */
    public java.lang.String getLastSeen() {
      java.lang.Object ref = lastSeen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastSeen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_seen = 9;</code>
     * @return The bytes for lastSeen.
     */
    public com.google.protobuf.ByteString
        getLastSeenBytes() {
      java.lang.Object ref = lastSeen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastSeen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_seen = 9;</code>
     * @param value The lastSeen to set.
     * @return This builder for chaining.
     */
    public Builder setLastSeen(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastSeen_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string last_seen = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastSeen() {
      lastSeen_ = getDefaultInstance().getLastSeen();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string last_seen = 9;</code>
     * @param value The bytes for lastSeen to set.
     * @return This builder for chaining.
     */
    public Builder setLastSeenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastSeen_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object mac_ = "";
    /**
     * <code>string mac = 10;</code>
     * @return The mac.
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mac = 10;</code>
     * @return The bytes for mac.
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mac = 10;</code>
     * @param value The mac to set.
     * @return This builder for chaining.
     */
    public Builder setMac(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mac_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMac() {
      mac_ = getDefaultInstance().getMac();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 10;</code>
     * @param value The bytes for mac to set.
     * @return This builder for chaining.
     */
    public Builder setMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mac_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object osMajorVersion_ = "";
    /**
     * <code>string os_major_version = 11;</code>
     * @return The osMajorVersion.
     */
    public java.lang.String getOsMajorVersion() {
      java.lang.Object ref = osMajorVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osMajorVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os_major_version = 11;</code>
     * @return The bytes for osMajorVersion.
     */
    public com.google.protobuf.ByteString
        getOsMajorVersionBytes() {
      java.lang.Object ref = osMajorVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osMajorVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_major_version = 11;</code>
     * @param value The osMajorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsMajorVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      osMajorVersion_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string os_major_version = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsMajorVersion() {
      osMajorVersion_ = getDefaultInstance().getOsMajorVersion();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string os_major_version = 11;</code>
     * @param value The bytes for osMajorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsMajorVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      osMajorVersion_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object osMinorVersion_ = "";
    /**
     * <code>string os_minor_version = 12;</code>
     * @return The osMinorVersion.
     */
    public java.lang.String getOsMinorVersion() {
      java.lang.Object ref = osMinorVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osMinorVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os_minor_version = 12;</code>
     * @return The bytes for osMinorVersion.
     */
    public com.google.protobuf.ByteString
        getOsMinorVersionBytes() {
      java.lang.Object ref = osMinorVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osMinorVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_minor_version = 12;</code>
     * @param value The osMinorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsMinorVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      osMinorVersion_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string os_minor_version = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsMinorVersion() {
      osMinorVersion_ = getDefaultInstance().getOsMinorVersion();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string os_minor_version = 12;</code>
     * @param value The bytes for osMinorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsMinorVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      osMinorVersion_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object aliases_ = "";
    /**
     * <code>string aliases = 13;</code>
     * @return The aliases.
     */
    public java.lang.String getAliases() {
      java.lang.Object ref = aliases_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aliases_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aliases = 13;</code>
     * @return The bytes for aliases.
     */
    public com.google.protobuf.ByteString
        getAliasesBytes() {
      java.lang.Object ref = aliases_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aliases_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aliases = 13;</code>
     * @param value The aliases to set.
     * @return This builder for chaining.
     */
    public Builder setAliases(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aliases_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string aliases = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAliases() {
      aliases_ = getDefaultInstance().getAliases();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string aliases = 13;</code>
     * @param value The bytes for aliases to set.
     * @return This builder for chaining.
     */
    public Builder setAliasesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aliases_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object addresses_ = "";
    /**
     * <code>string addresses = 14;</code>
     * @return The addresses.
     */
    public java.lang.String getAddresses() {
      java.lang.Object ref = addresses_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addresses_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string addresses = 14;</code>
     * @return The bytes for addresses.
     */
    public com.google.protobuf.ByteString
        getAddressesBytes() {
      java.lang.Object ref = addresses_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addresses_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string addresses = 14;</code>
     * @param value The addresses to set.
     * @return This builder for chaining.
     */
    public Builder setAddresses(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      addresses_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string addresses = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddresses() {
      addresses_ = getDefaultInstance().getAddresses();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string addresses = 14;</code>
     * @param value The bytes for addresses to set.
     * @return This builder for chaining.
     */
    public Builder setAddressesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      addresses_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:agent.Agent)
  }

  // @@protoc_insertion_point(class_scope:agent.Agent)
  private static final com.park.utmstack.service.grpc.Agent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.park.utmstack.service.grpc.Agent();
  }

  public static com.park.utmstack.service.grpc.Agent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Agent>
      PARSER = new com.google.protobuf.AbstractParser<Agent>() {
    @java.lang.Override
    public Agent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Agent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Agent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.park.utmstack.service.grpc.Agent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

