// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.park.utmstack.service.grpc;

public interface AgentCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.AgentCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 2;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 2;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>uint32 agent_id = 3;</code>
   * @return The agentId.
   */
  int getAgentId();

  /**
   * <code>string command = 4;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 4;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>.agent.AgentCommandStatus command_status = 5;</code>
   * @return The enum numeric value on the wire for commandStatus.
   */
  int getCommandStatusValue();
  /**
   * <code>.agent.AgentCommandStatus command_status = 5;</code>
   * @return The commandStatus.
   */
  com.park.utmstack.service.grpc.AgentCommandStatus getCommandStatus();

  /**
   * <code>string result = 6;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 6;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>string executed_by = 7;</code>
   * @return The executedBy.
   */
  java.lang.String getExecutedBy();
  /**
   * <code>string executed_by = 7;</code>
   * @return The bytes for executedBy.
   */
  com.google.protobuf.ByteString
      getExecutedByBytes();

  /**
   * <code>string cmd_id = 8;</code>
   * @return The cmdId.
   */
  java.lang.String getCmdId();
  /**
   * <code>string cmd_id = 8;</code>
   * @return The bytes for cmdId.
   */
  com.google.protobuf.ByteString
      getCmdIdBytes();

  /**
   * <code>.agent.Agent agent = 9;</code>
   * @return Whether the agent field is set.
   */
  boolean hasAgent();
  /**
   * <code>.agent.Agent agent = 9;</code>
   * @return The agent.
   */
  com.park.utmstack.service.grpc.Agent getAgent();
  /**
   * <code>.agent.Agent agent = 9;</code>
   */
  com.park.utmstack.service.grpc.AgentOrBuilder getAgentOrBuilder();

  /**
   * <code>string reason = 10;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 10;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>string origin_type = 11;</code>
   * @return The originType.
   */
  java.lang.String getOriginType();
  /**
   * <code>string origin_type = 11;</code>
   * @return The bytes for originType.
   */
  com.google.protobuf.ByteString
      getOriginTypeBytes();

  /**
   * <code>string origin_id = 12;</code>
   * @return The originId.
   */
  java.lang.String getOriginId();
  /**
   * <code>string origin_id = 12;</code>
   * @return The bytes for originId.
   */
  com.google.protobuf.ByteString
      getOriginIdBytes();
}
