// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.park.utmstack.service.grpc;

public final class AgentManagerGrpc {
  private AgentManagerGrpc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AgentManagerGrpc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_AgentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_AgentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_ListAgentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_ListAgentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_Agent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_Agent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_BidirectionalStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_BidirectionalStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_UtmCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_UtmCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_CommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_CommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_ListAgentsCommandsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_ListAgentsCommandsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_AgentCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_AgentCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013agent.proto\022\005agent\032\037google/protobuf/ti" +
      "mestamp.proto\032\014common.proto\"\325\001\n\014AgentReq" +
      "uest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\n\n\002os" +
      "\030\003 \001(\t\022\020\n\010platform\030\004 \001(\t\022\017\n\007version\030\005 \001(" +
      "\t\022\023\n\013register_by\030\006 \001(\t\022\013\n\003mac\030\007 \001(\t\022\030\n\020o" +
      "s_major_version\030\010 \001(\t\022\030\n\020os_minor_versio" +
      "n\030\t \001(\t\022\017\n\007aliases\030\n \001(\t\022\021\n\taddresses\030\013 " +
      "\001(\t\"?\n\022ListAgentsResponse\022\032\n\004rows\030\001 \003(\0132" +
      "\014.agent.Agent\022\r\n\005total\030\002 \001(\005\"\212\002\n\005Agent\022\n" +
      "\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\n\n\002os\030\003 \001(\t" +
      "\022\035\n\006status\030\004 \001(\0162\r.agent.Status\022\020\n\010platf" +
      "orm\030\005 \001(\t\022\017\n\007version\030\006 \001(\t\022\021\n\tagent_key\030" +
      "\007 \001(\t\022\n\n\002id\030\010 \001(\r\022\021\n\tlast_seen\030\t \001(\t\022\013\n\003" +
      "mac\030\n \001(\t\022\030\n\020os_major_version\030\013 \001(\t\022\030\n\020o" +
      "s_minor_version\030\014 \001(\t\022\017\n\007aliases\030\r \001(\t\022\021" +
      "\n\taddresses\030\016 \001(\t\"u\n\023BidirectionalStream" +
      "\022$\n\007command\030\001 \001(\0132\021.agent.UtmCommandH\000\022&" +
      "\n\006result\030\002 \001(\0132\024.agent.CommandResultH\000B\020" +
      "\n\016stream_message\"\233\001\n\nUtmCommand\022\020\n\010agent" +
      "_id\030\001 \001(\t\022\017\n\007command\030\002 \001(\t\022\023\n\013executed_b" +
      "y\030\003 \001(\t\022\016\n\006cmd_id\030\004 \001(\t\022\023\n\013origin_type\030\005" +
      " \001(\t\022\021\n\torigin_id\030\006 \001(\t\022\016\n\006reason\030\007 \001(\t\022" +
      "\r\n\005shell\030\010 \001(\t\"r\n\rCommandResult\022\020\n\010agent" +
      "_id\030\001 \001(\t\022\016\n\006result\030\002 \001(\t\022/\n\013executed_at" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006cm" +
      "d_id\030\004 \001(\t\"N\n\032ListAgentsCommandsResponse" +
      "\022!\n\004rows\030\001 \003(\0132\023.agent.AgentCommand\022\r\n\005t" +
      "otal\030\002 \001(\005\"\261\002\n\014AgentCommand\022.\n\ncreated_a" +
      "t\030\001 \001(\0132\032.google.protobuf.Timestamp\022.\n\nu" +
      "pdated_at\030\002 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\020\n\010agent_id\030\003 \001(\r\022\017\n\007command\030\004 \001(\t\0221" +
      "\n\016command_status\030\005 \001(\0162\031.agent.AgentComm" +
      "andStatus\022\016\n\006result\030\006 \001(\t\022\023\n\013executed_by" +
      "\030\007 \001(\t\022\016\n\006cmd_id\030\010 \001(\t\022\016\n\006reason\030\t \001(\t\022\023" +
      "\n\013origin_type\030\n \001(\t\022\021\n\torigin_id\030\013 \001(\t*W" +
      "\n\022AgentCommandStatus\022\020\n\014NOT_EXECUTED\020\000\022\t" +
      "\n\005QUEUE\020\001\022\013\n\007PENDING\020\002\022\014\n\010EXECUTED\020\003\022\t\n\005" +
      "ERROR\020\0042\234\003\n\014AgentService\0229\n\013UpdateAgent\022" +
      "\023.agent.AgentRequest\032\023.agent.AuthRespons" +
      "e\"\000\022;\n\rRegisterAgent\022\023.agent.AgentReques" +
      "t\032\023.agent.AuthResponse\"\000\022:\n\013DeleteAgent\022" +
      "\024.agent.DeleteRequest\032\023.agent.AuthRespon" +
      "se\"\000\022=\n\nListAgents\022\022.agent.ListRequest\032\031" +
      ".agent.ListAgentsResponse\"\000\022K\n\013AgentStre" +
      "am\022\032.agent.BidirectionalStream\032\032.agent.B" +
      "idirectionalStream\"\000(\0010\001\022L\n\021ListAgentCom" +
      "mands\022\022.agent.ListRequest\032!.agent.ListAg" +
      "entsCommandsResponse\"\0002O\n\014PanelService\022?" +
      "\n\016ProcessCommand\022\021.agent.UtmCommand\032\024.ag" +
      "ent.CommandResult\"\000(\0010\001B7\n\036com.park.utms" +
      "tack.service.grpcB\020AgentManagerGrpcP\001\210\001\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.park.utmstack.service.grpc.Common.getDescriptor(),
        });
    internal_static_agent_AgentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agent_AgentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_AgentRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "Os", "Platform", "Version", "RegisterBy", "Mac", "OsMajorVersion", "OsMinorVersion", "Aliases", "Addresses", });
    internal_static_agent_ListAgentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agent_ListAgentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_ListAgentsResponse_descriptor,
        new java.lang.String[] { "Rows", "Total", });
    internal_static_agent_Agent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_agent_Agent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_Agent_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "Os", "Status", "Platform", "Version", "AgentKey", "Id", "LastSeen", "Mac", "OsMajorVersion", "OsMinorVersion", "Aliases", "Addresses", });
    internal_static_agent_BidirectionalStream_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_agent_BidirectionalStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_BidirectionalStream_descriptor,
        new java.lang.String[] { "Command", "Result", "StreamMessage", });
    internal_static_agent_UtmCommand_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_agent_UtmCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_UtmCommand_descriptor,
        new java.lang.String[] { "AgentId", "Command", "ExecutedBy", "CmdId", "OriginType", "OriginId", "Reason", "Shell", });
    internal_static_agent_CommandResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_agent_CommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_CommandResult_descriptor,
        new java.lang.String[] { "AgentId", "Result", "ExecutedAt", "CmdId", });
    internal_static_agent_ListAgentsCommandsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_agent_ListAgentsCommandsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_ListAgentsCommandsResponse_descriptor,
        new java.lang.String[] { "Rows", "Total", });
    internal_static_agent_AgentCommand_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_agent_AgentCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_agent_AgentCommand_descriptor,
        new java.lang.String[] { "CreatedAt", "UpdatedAt", "AgentId", "Command", "CommandStatus", "Result", "ExecutedBy", "CmdId", "Reason", "OriginType", "OriginId", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.park.utmstack.service.grpc.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
