// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.park.utmstack.service.grpc;

public interface AgentGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.AgentGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string group_name = 2;</code>
   * @return The groupName.
   */
  java.lang.String getGroupName();
  /**
   * <code>string group_name = 2;</code>
   * @return The bytes for groupName.
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>string group_description = 3;</code>
   * @return The groupDescription.
   */
  java.lang.String getGroupDescription();
  /**
   * <code>string group_description = 3;</code>
   * @return The bytes for groupDescription.
   */
  com.google.protobuf.ByteString
      getGroupDescriptionBytes();
}
