// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.park.utmstack.service.grpc;

public interface ListAgentsTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ListAgentsTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .agent.AgentType rows = 1;</code>
   */
  java.util.List<com.park.utmstack.service.grpc.AgentType> 
      getRowsList();
  /**
   * <code>repeated .agent.AgentType rows = 1;</code>
   */
  com.park.utmstack.service.grpc.AgentType getRows(int index);
  /**
   * <code>repeated .agent.AgentType rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .agent.AgentType rows = 1;</code>
   */
  java.util.List<? extends com.park.utmstack.service.grpc.AgentTypeOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .agent.AgentType rows = 1;</code>
   */
  com.park.utmstack.service.grpc.AgentTypeOrBuilder getRowsOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();
}
