name: Agent Manager QA

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'agent-manager/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: agent-manager
      environment: v10-qa
      directory: agent-manager
      binary: server
      branch: qa
