name: Backend - RELEASE
on:
  push:
    tags: [ 'v*' ]
    paths:
      - 'backend/**'
      - 'version.yml'

jobs:
  docker:
    uses: ./.github/workflows/docker-java-11.yml
    with:
      image_name: backend
      environment: v10
      directory: backend
      branch: rc
