name: UTMStack API - RC
on:
  push:
    branches: [ "rc" ]
    paths:
      - 'backend/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: backend
      environment: v10-rc
      directory: backend
      branch: rc
