name: Create and Publish Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      tag_message:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Set env
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: ./mutate
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}_${{ env.TAG }},ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{inputs.environment}}_${{ env.TAG }}"
          message: ${{inputs.tag_message}}
