name: Correlation QA

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'correlation/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: correlation
      environment: v10-qa
      directory: correlation
      binary: correlation
      branch: qa
