name: Docker Image Java
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          
      - name: Read version from config
        id: read_version
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: version.yml
          version: version     

      - name: Build with Maven
        working-directory: ./${{inputs.directory}}
        run: |
          echo "Building with maven"
          echo "The configured version is: ${{steps.read_version.outputs.version}}"
          mvn -B -Drevision=${{steps.read_version.outputs.version}} -Pprod clean package -s settings.xml
        env:
          MAVEN_TK: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: /home/runner/work/UTMStack/UTMStack/${{inputs.directory}}/
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}
