name: Docker Image Java
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./${{inputs.directory}}
        run: |
          echo "Building with maven"
          mvn clean install -U -s settings.xml
        env:
          MAVEN_TK: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: /home/runner/work/UTMStack/UTMStack/${{inputs.directory}}/
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}
