name: Event Processor

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: ./etc/threatwinds
          push: true
          tags: ghcr.io/utmstack/utmstack/eventprocessor:${{inputs.environment}}