name: Frontend Dev

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-frontend.yml
    with:
      image_name: frontend
      environment: v10-dev
      directory: frontend
      branch: main
