name: Frontend QA

on:
  pull_request:
    branches: [ "rc" ]
    paths:
      - 'frontend/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-frontend.yml
    with:
      image_name: frontend
      environment: v10-qa
      directory: frontend
      branch: main
