name: Frontend Release

on:
  push:
    tags: [ 'v*' ]
    paths:
      - 'frontend/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-frontend.yml
    with:
      image_name: frontend
      environment: v10
      directory: frontend
      branch: rc
