name: Installer Dev

on:
  workflow_run:
    workflows: ["Frontend Dev", "Backend Dev", "User Auditor Dev", "Web PDF Dev", "Log Auth Proxy Dev", "Agent Manager Dev", "Correlation Dev", "Bitdefender Dev", "Mutate Dev", "O365 Dev"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: dev
    steps:
    - name: Check out code into the right branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20 
      id: go

    - name: Get dependencies
      working-directory: ./installer
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      working-directory: ./installer
      run: go test -v .

    - name: Build
      working-directory: ./installer
      env:
        GOOS: linux
        GOARCH: amd64
      run: |
        go build -o installer -v .
        mv installer /home/utmstack/installer
        chmod +x /home/utmstack/installer

    - name: Run
      id: run_installer
      working-directory: /home/utmstack
      run: |
          sudo ./installer

    - name: Open ports
      id: open_ports
      working-directory: /home/utmstack
      run: |
          sudo docker service update --publish-add 9200:9200 utmstack_node1 & docker service update --publish-add 5432:5432 utmstack_postgres
