name: O365 RC

on:
  push:
    branches: [ "rc" ]
    paths:
      - 'office365/**'
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: office365
      environment: v10-rc
      directory: office365
      binary: o365_integration
