name: O365 Integration Build QA

on:
  pull_request:
    branches: [ "rc" ]
    paths:
      - 'office365/**'
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/integrations-o365-build-image.yml
    with:
      image_name: office365
      environment: v10-qa
      branch: ''
      tag_message: "Automatic Tag Deployed to testing env"
