name: Create and Publish O365 Integration Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      tag_message:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: "Print tag"
        run: echo "Creating image with tag ${{env.TAG}}"

      - uses: actions/checkout@v3
        with:
            ref: ${{inputs.branch}}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
            go-version: ^1.20
        id: go
  
      - name: Build Binary
        working-directory: ./office365
        run: go build -o o365_integration -v .
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: ./office365
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}_${{ env.TAG }},ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{inputs.environment}}_${{ env.TAG }}"
          message: ${{inputs.tag_message}}
