name: Bitdefender QA

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'bdgz/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: bitdefender
      environment: v10-qa
      directory: bdgz
      binary: bdgz_integration
      branch: qa
