name: Bitdefender Integration Build QA

on:
  pull_request:
    branches: [ "rc" ]
    paths:
      - 'bdgz/**'
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/integrations-build-image.yml
    with:
      image_name: bitdefender
      environment: v10-qa
      directory: bdgz
      binary: bdgz_integration
