name: Mutate Dev

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mutate/**'

  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-basic.yml
    with:
      image_name: mutate
      environment: v10-dev
      directory: mutate
        
