name: O365 Integration Build Release

on:
  push:
    tags: 
      - 'v*'
    paths:
      - 'office365/**'
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/integrations-build-image.yml
    with:
      image_name: office365
      environment: v10
      directory: office365
      binary: o365_integration
  
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: "Print tag"
        run: echo "Creating image with tag ${{env.TAG}}"

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v10_${{ env.TAG }}
          message: "Automatic Tag Deployed to production"
