name: Log Auth Proxy QA

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'log-auth-proxy/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: log-auth-proxy
      environment: v10-qa
      directory: log-auth-proxy
      binary: server
      branch: qa
