# This is a basic workflow to help you get started with Actions

name: UTM MUTATE BUILD QA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
    paths:
      - 'mutate/**'

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    uses: ./.github/workflows/build-image-mutate.yml
    with:
      image_name: mutate
      environment: v10-qa
      branch: ''
      tag_message: "Automatic Tag Release Candidate"