name: Plugins Build

on:
  push:
    branches: [ 'feature/**' ]
    paths:
      - 'plugins/**'
      - 'pipelines/**'

jobs:
  check:
    name: Checking
    runs-on: ubuntu-latest
    outputs:
      env_version: ${{ steps.set-env.outputs.env_version }}
    steps:
      - name: Determine Build Environment
        id: set-env
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') }}; then
            echo "DEV environment"
            echo "env_version=v10-dev" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build and push to Google CDN
    needs: check
    if: needs.check.outputs.env_version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Build and push plugins
        id: set-env
        run: |
          export DEPLOY_ENV=${{ needs.check.outputs.env_version }}
          python -m pip install --upgrade pip
          pip install google-cloud-storage
          
          export GOOS=linux
          export GOARCH=amd64
          cd ${{ github.workspace }}/plugins
          make build

          export GCP_KEY='${{ secrets.GCP_KEY }}'
          cd ${{ github.workspace }}/.github/scripts
          python plugins-deploy.py $DEPLOY_ENV