name: Docker Image Java 11

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"    

      - name: Build with Maven
        working-directory: ./${{inputs.image_name}}
        run: |
          echo "Building with maven"
          echo "The configured version is: ${{ inputs.version }}"
          mvn -B -Drevision=${{ inputs.version }} -Pprod clean package -s settings.xml
        env:
          MAVEN_TK: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v6
        with:
          context: /home/runner/work/UTMStack/UTMStack/${{inputs.image_name}}/
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.tag}}