name: Docker Image Java 11

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4
      
      - name: Load Version
        id: set-version
        run: |
          versions=$(cat "${{ github.workspace }}/versions.json")
          service_version=$(echo "${versions}" | jq -r --arg s "${{inputs.image_name}}" '.[$s]')
          master_version=$(echo "${versions}" | jq -r --arg s "master-version" '.[$s]')
          echo "version=${service_version}" >> "$GITHUB_OUTPUT"
          echo "master_version=${master_version}" >> "$GITHUB_OUTPUT"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"  

      - name: Build with Maven
        working-directory: ./${{inputs.image_name}}
        run: |
          echo "Building with maven"
          echo "The configured version is: ${{ steps.set-version.outputs.master_version }}"
          mvn -B -Drevision=${{ steps.set-version.outputs.master_version }} -Pprod clean package -s settings.xml
        env:
          MAVEN_TK: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image for Components v11
        if: ${{ inputs.environment != 'v10-dev' }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{inputs.image_name}}
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:v${{ steps.set-version.outputs.version }}-${{inputs.environment}}
      
      - name: Build and Push the Image for v10
        if : ${{ inputs.environment == 'v10-dev' }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{inputs.image_name}}
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}