name: User Auditor Release
on:
  push:
    tags: [ 'v*' ]
    paths:
      - 'user-auditor/**'
  workflow_dispatch:
jobs:
  docker-image-java:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: user-auditor
      environment: v10
      directory: user-auditor
