name: User Auditor QA
on:
  push:
    branches: [ "qa" ]
    paths:
      - 'user-auditor/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: user-auditor
      environment: v10-qa
      directory: user-auditor
      branch: qa
