name: User Auditor RC
on:
  push:
    branches: [ "rc" ]
    paths:
      - 'user-auditor/**'
  workflow_dispatch:
jobs:
  docker-image-java:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: user-auditor
      environment: v10-rc
      directory: user-auditor
