name: User Auditor RC
on:
  push:
    branches: [ "rc" ]
    paths:
      - 'user-auditor/**'
  workflow_dispatch:
jobs:
  docker-native-image-java:
    uses: ./.github/workflows/user-auditor-docker.yml
    with:
      image_name: user-auditor
      environment: v10-rc
      directory: user-auditor
