name: Docker Image Golang

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code into the right branch
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20
        id: go

      - name: Running Tests
        working-directory: ./${{inputs.image_name}}
        run: go test -v ./...
  
      - name: Build Binary
        working-directory: ./${{inputs.image_name}}
        run: go build -o ${{inputs.image_name}} -v .
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: utmstack
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v6
        with:
          context: ./${{inputs.image_name}}
          push: true
          tags: ghcr.io/utmstack/utmstack/${{inputs.image_name}}:${{inputs.environment}}
