name: Web PDF QA
on:
  push:
    branches: [ "qa" ]
    paths:
      - 'web-pdf/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: web-pdf
      environment: v10-qa
      directory: web-pdf
      branch: qa
