package schema

type AlertGPTDetails struct {
	Timestamp         string   `json:"@timestamp"`
	ID                string   `json:"id"`
	ParentID          *string  `json:"parentId,omitempty"`
	Status            int      `json:"status"`
	StatusLabel       string   `json:"statusLabel"`
	StatusObservation string   `json:"statusObservation"`
	IsIncident        bool     `json:"isIncident"`
	Name              string   `json:"name"`
	Category          string   `json:"category"`
	Severity          int      `json:"severity"`
	SeverityLabel     string   `json:"severityLabel"`
	Description       string   `json:"description"`
	Solution          string   `json:"solution"`
	Technique         string   `json:"technique"`
	Reference         []string `json:"reference"`
	DataType          string   `json:"dataType"`
	ImpactScore       int32    `json:"impactScore"`
	DataSource        string   `json:"dataSource"`
	Tags              []string `json:"tags"`
	Notes             string   `json:"notes"`
	TagRulesApplied   []int    `json:"tagRulesApplied"`
	DeduplicatedBy    []string `json:"deduplicatedBy"`

	IncidentCreatedBy    string `json:"incidentCreatedBy"`
	IncidentObservation  string `json:"incidentObservation"`
	IncidentCreationDate string `json:"incidentCreationDate"`
	IncidentSource       string `json:"incidentSource"`

	ImpactConfidentiality int32 `json:"impact_confidentiality,omitempty"`
	ImpactIntegrity       int32 `json:"impact_integrity,omitempty"`
	ImpactAvailability    int32 `json:"impact_availability,omitempty"`

	EventsId               string   `json:"events_id,omitempty"`
	EventsTimestamp        string   `json:"events_timestamp,omitempty"`
	EventsDeviceTime       string   `json:"events_deviceTime,omitempty"`
	EventsDataType         string   `json:"events_dataType,omitempty"`
	EventsDataSource       string   `json:"events_dataSource,omitempty"`
	EventsTenantId         string   `json:"events_tenantId,omitempty"`
	EventsTenantName       string   `json:"events_tenantName,omitempty"`
	EventsRaw              string   `json:"events_raw,omitempty"`
	EventsLog              []string `json:"events_log,omitempty"`
	EventsProtocol         string   `json:"events_protocol,omitempty"`
	EventsConnectionStatus string   `json:"events_connectionStatus,omitempty"`
	EventsStatusCode       int64    `json:"events_statusCode,omitempty"`
	EventsActionResult     string   `json:"events_actionResult,omitempty"`
	EventsAction           string   `json:"events_action,omitempty"`
	EventsCommand          string   `json:"events_command,omitempty"`
	EventsSeverity         string   `json:"events_severity,omitempty"`

	LastEventId               string   `json:"last_event_id,omitempty"`
	LastEventTimestamp        string   `json:"last_event_timestamp,omitempty"`
	LastEventDeviceTime       string   `json:"last_event_deviceTime,omitempty"`
	LastEventDataType         string   `json:"last_event_dataType,omitempty"`
	LastEventDataSource       string   `json:"last_event_dataSource,omitempty"`
	LastEventTenantId         string   `json:"last_event_tenantId,omitempty"`
	LastEventTenantName       string   `json:"last_event_tenantName,omitempty"`
	LastEventRaw              string   `json:"last_event_raw,omitempty"`
	LastEventLog              []string `json:"last_event_log,omitempty"`
	LastEventProtocol         string   `json:"last_event_protocol,omitempty"`
	LastEventConnectionStatus string   `json:"last_event_connectionStatus,omitempty"`
	LastEventStatusCode       int64    `json:"last_event_statusCode,omitempty"`
	LastEventActionResult     string   `json:"last_event_actionResult,omitempty"`
	LastEventAction           string   `json:"last_event_action,omitempty"`
	LastEventCommand          string   `json:"last_event_command,omitempty"`
	LastEventSeverity         string   `json:"last_event_severity,omitempty"`

	AdversaryBytesSent        float64 `json:"adversary_bytesSent,omitempty"`
	AdversaryBytesReceived    float64 `json:"adversary_bytesReceived,omitempty"`
	AdversaryPackagesSent     int64   `json:"adversary_packagesSent,omitempty"`
	AdversaryPackagesReceived int64   `json:"adversary_packagesReceived,omitempty"`
	AdversaryConnections      int64   `json:"adversary_connections,omitempty"`
	AdversaryUsedCpuPercent   int64   `json:"adversary_usedCpuPercent,omitempty"`
	AdversaryUsedMemPercent   int64   `json:"adversary_usedMemPercent,omitempty"`
	AdversaryTotalCpuUnits    int64   `json:"adversary_totalCpuUnits,omitempty"`
	AdversaryTotalMem         int64   `json:"adversary_totalMem,omitempty"`
	AdversaryIp               string  `json:"adversary_ip,omitempty"`
	AdversaryHost             string  `json:"adversary_host,omitempty"`
	AdversaryUser             string  `json:"adversary_user,omitempty"`
	AdversaryGroup            string  `json:"adversary_group,omitempty"`
	AdversaryPort             int64   `json:"adversary_port,omitempty"`
	AdversaryDomain           string  `json:"adversary_domain,omitempty"`
	AdversaryFqdn             string  `json:"adversary_fqdn,omitempty"`
	AdversaryMac              string  `json:"adversary_mac,omitempty"`
	AdversaryProcess          string  `json:"adversary_process,omitempty"`
	AdversaryFile             string  `json:"adversary_file,omitempty"`
	AdversaryPath             string  `json:"adversary_path,omitempty"`
	AdversaryHash             string  `json:"adversary_hash,omitempty"`
	AdversaryUrl              string  `json:"adversary_url,omitempty"`
	AdversaryEmail            string  `json:"adversary_email,omitempty"`

	AdversaryGeolocationCountry     string  `json:"adversary_geolocationCountry,omitempty"`
	AdversaryGeolocationCity        string  `json:"adversary_geolocationCity,omitempty"`
	AdversaryGeolocationLatitude    float64 `json:"adversary_geolocationLatitude,omitempty"`
	AdversaryGeolocationLongitude   float64 `json:"adversary_geolocationLongitude,omitempty"`
	AdversaryGeolocationAsn         int64   `json:"adversary_geolocationAsn,omitempty"`
	AdversaryGeolocationAso         string  `json:"adversary_geolocationAso,omitempty"`
	AdversaryGeolocationCountryCode string  `json:"adversary_geolocationcCuntryCode,omitempty"`
	AdversaryGeolocationAccuracy    int32   `json:"adversary_geolocationaAcuracy,omitempty"`

	TargetBytesSent        float64 `json:"target_bytesSent,omitempty"`
	TargetBytesReceived    float64 `json:"target_bytesReceived,omitempty"`
	TargetPackagesSent     int64   `json:"target_packagesSent,omitempty"`
	TargetPackagesReceived int64   `json:"target_packagesReceived,omitempty"`
	TargetConnections      int64   `json:"target_connections,omitempty"`
	TargetUsedCpuPercent   int64   `json:"target_usedCpuPercent,omitempty"`
	TargetUsedMemPercent   int64   `json:"target_usedMemPercent,omitempty"`
	TargetTotalCpuUnits    int64   `json:"target_totalCpuUnits,omitempty"`
	TargetTotalMem         int64   `json:"target_totalMem,omitempty"`
	TargetIp               string  `json:"target_ip,omitempty"`
	TargetHost             string  `json:"target_host,omitempty"`
	TargetUser             string  `json:"target_user,omitempty"`
	TargetGroup            string  `json:"target_group,omitempty"`
	TargetPort             int64   `json:"target_port,omitempty"`
	TargetDomain           string  `json:"target_domain,omitempty"`
	TargetFqdn             string  `json:"target_fqdn,omitempty"`
	TargetMac              string  `json:"target_mac,omitempty"`
	TargetProcess          string  `json:"target_process,omitempty"`
	TargetFile             string  `json:"target_file,omitempty"`
	TargetPath             string  `json:"target_path,omitempty"`
	TargetHash             string  `json:"target_hash,omitempty"`
	TargetUrl              string  `json:"target_url,omitempty"`
	TargetEmail            string  `json:"target_email,omitempty"`

	TargetGeolocationCountry     string  `json:"target_geolocationCountry,omitempty"`
	TargetGeolocationCity        string  `json:"target_geolocationCity,omitempty"`
	TargetGeolocationLatitude    float64 `json:"target_geolocationLatitude,omitempty"`
	TargetGeolocationLongitude   float64 `json:"target_geolocationLongitude,omitempty"`
	TargetGeolocationAsn         int64   `json:"target_geolocationAsn,omitempty"`
	TargetGeolocationAso         string  `json:"target_geolocationAso,omitempty"`
	TargetGeolocationCountryCode string  `json:"target_geolocationcCuntryCode,omitempty"`
	TargetGeolocationAccuracy    int32   `json:"target_geolocationaAcuracy,omitempty"`

	EventOriginBytesSent        float64 `json:"event_origin_bytesSent,omitempty"`
	EventOriginBytesReceived    float64 `json:"event_origin_bytesReceived,omitempty"`
	EventOriginPackagesSent     int64   `json:"event_origin_packagesSent,omitempty"`
	EventOriginPackagesReceived int64   `json:"event_origin_packagesReceived,omitempty"`
	EventOriginConnections      int64   `json:"event_origin_connections,omitempty"`
	EventOriginUsedCpuPercent   int64   `json:"event_origin_usedCpuPercent,omitempty"`
	EventOriginUsedMemPercent   int64   `json:"event_origin_usedMemPercent,omitempty"`
	EventOriginTotalCpuUnits    int64   `json:"event_origin_totalCpuUnits,omitempty"`
	EventOriginTotalMem         int64   `json:"event_origin_totalMem,omitempty"`
	EventOriginIp               string  `json:"event_origin_ip,omitempty"`
	EventOriginHost             string  `json:"event_origin_host,omitempty"`
	EventOriginUser             string  `json:"event_origin_user,omitempty"`
	EventOriginGroup            string  `json:"event_origin_group,omitempty"`
	EventOriginPort             int64   `json:"event_origin_port,omitempty"`
	EventOriginDomain           string  `json:"event_origin_domain,omitempty"`
	EventOriginFqdn             string  `json:"event_origin_fqdn,omitempty"`
	EventOriginMac              string  `json:"event_origin_mac,omitempty"`
	EventOriginProcess          string  `json:"event_origin_process,omitempty"`
	EventOriginFile             string  `json:"event_origin_file,omitempty"`
	EventOriginPath             string  `json:"event_origin_path,omitempty"`
	EventOriginHash             string  `json:"event_origin_hash,omitempty"`
	EventOriginUrl              string  `json:"event_origin_url,omitempty"`
	EventOriginEmail            string  `json:"event_origin_email,omitempty"`

	EventOriginGeolocationCountry     string  `json:"event_origin_geolocationCountry,omitempty"`
	EventOriginGeolocationCity        string  `json:"event_origin_geolocationCity,omitempty"`
	EventOriginGeolocationLatitude    float64 `json:"event_origin_geolocationLatitude,omitempty"`
	EventOriginGeolocationLongitude   float64 `json:"event_origin_geolocationLongitude,omitempty"`
	EventOriginGeolocationAsn         int64   `json:"event_origin_geolocationAsn,omitempty"`
	EventOriginGeolocationAso         string  `json:"event_origin_geolocationAso,omitempty"`
	EventOriginGeolocationCountryCode string  `json:"event_origin_geolocationcCuntryCode,omitempty"`
	EventOriginGeolocationAccuracy    int32   `json:"event_origin_geolocationaAcuracy,omitempty"`

	EventTargetBytesSent        float64 `json:"event_target_bytesSent,omitempty"`
	EventTargetBytesReceived    float64 `json:"event_target_bytesReceived,omitempty"`
	EventTargetPackagesSent     int64   `json:"event_target_packagesSent,omitempty"`
	EventTargetPackagesReceived int64   `json:"event_target_packagesReceived,omitempty"`
	EventTargetConnections      int64   `json:"event_target_connections,omitempty"`
	EventTargetUsedCpuPercent   int64   `json:"event_target_usedCpuPercent,omitempty"`
	EventTargetUsedMemPercent   int64   `json:"event_target_usedMemPercent,omitempty"`
	EventTargetTotalCpuUnits    int64   `json:"event_target_totalCpuUnits,omitempty"`
	EventTargetTotalMem         int64   `json:"event_target_totalMem,omitempty"`
	EventTargetIp               string  `json:"event_target_ip,omitempty"`
	EventTargetHost             string  `json:"event_target_host,omitempty"`
	EventTargetUser             string  `json:"event_target_user,omitempty"`
	EventTargetGroup            string  `json:"event_target_group,omitempty"`
	EventTargetPort             int64   `json:"event_target_port,omitempty"`
	EventTargetDomain           string  `json:"event_target_domain,omitempty"`
	EventTargetFqdn             string  `json:"event_target_fqdn,omitempty"`
	EventTargetMac              string  `json:"event_target_mac,omitempty"`
	EventTargetProcess          string  `json:"event_target_process,omitempty"`
	EventTargetFile             string  `json:"event_target_file,omitempty"`
	EventTargetPath             string  `json:"event_target_path,omitempty"`
	EventTargetHash             string  `json:"event_target_hash,omitempty"`
	EventTargetUrl              string  `json:"event_target_url,omitempty"`
	EventTargetEmail            string  `json:"event_target_email,omitempty"`

	EventTargetGeolocationCountry     string  `json:"event_target_geolocationCountry,omitempty"`
	EventTargetGeolocationCity        string  `json:"event_target_geolocationCity,omitempty"`
	EventTargetGeolocationLatitude    float64 `json:"event_target_geolocationLatitude,omitempty"`
	EventTargetGeolocationLongitude   float64 `json:"event_target_geolocationLongitude,omitempty"`
	EventTargetGeolocationAsn         int64   `json:"event_target_geolocationAsn,omitempty"`
	EventTargetGeolocationAso         string  `json:"event_target_geolocationAso,omitempty"`
	EventTargetGeolocationCountryCode string  `json:"event_target_geolocationcCuntryCode,omitempty"`
	EventTargetGeolocationAccuracy    int32   `json:"event_target_geolocationaAcuracy,omitempty"`

	LastEventOriginBytesSent        float64 `json:"last_event_origin_bytesSent,omitempty"`
	LastEventOriginBytesReceived    float64 `json:"last_event_origin_bytesReceived,omitempty"`
	LastEventOriginPackagesSent     int64   `json:"last_event_origin_packagesSent,omitempty"`
	LastEventOriginPackagesReceived int64   `json:"last_event_origin_packagesReceived,omitempty"`
	LastEventOriginConnections      int64   `json:"last_event_origin_connections,omitempty"`
	LastEventOriginUsedCpuPercent   int64   `json:"last_event_origin_usedCpuPercent,omitempty"`
	LastEventOriginUsedMemPercent   int64   `json:"last_event_origin_usedMemPercent,omitempty"`
	LastEventOriginTotalCpuUnits    int64   `json:"last_event_origin_totalCpuUnits,omitempty"`
	LastEventOriginTotalMem         int64   `json:"last_event_origin_totalMem,omitempty"`
	LastEventOriginIp               string  `json:"last_event_origin_ip,omitempty"`
	LastEventOriginHost             string  `json:"last_event_origin_host,omitempty"`
	LastEventOriginUser             string  `json:"last_event_origin_user,omitempty"`
	LastEventOriginGroup            string  `json:"last_event_origin_group,omitempty"`
	LastEventOriginPort             int64   `json:"last_event_origin_port,omitempty"`
	LastEventOriginDomain           string  `json:"last_event_origin_domain,omitempty"`
	LastEventOriginFqdn             string  `json:"last_event_origin_fqdn,omitempty"`
	LastEventOriginMac              string  `json:"last_event_origin_mac,omitempty"`
	LastEventOriginProcess          string  `json:"last_event_origin_process,omitempty"`
	LastEventOriginFile             string  `json:"last_event_origin_file,omitempty"`
	LastEventOriginPath             string  `json:"last_event_origin_path,omitempty"`
	LastEventOriginHash             string  `json:"last_event_origin_hash,omitempty"`
	LastEventOriginUrl              string  `json:"last_event_origin_url,omitempty"`
	LastEventOriginEmail            string  `json:"last_event_origin_email,omitempty"`

	LastEventOriginGeolocationCountry     string  `json:"last_event_origin_geolocationCountry,omitempty"`
	LastEventOriginGeolocationCity        string  `json:"last_event_origin_geolocationCity,omitempty"`
	LastEventOriginGeolocationLatitude    float64 `json:"last_event_origin_geolocationLatitude,omitempty"`
	LastEventOriginGeolocationLongitude   float64 `json:"last_event_origin_geolocationLongitude,omitempty"`
	LastEventOriginGeolocationAsn         int64   `json:"last_event_origin_geolocationAsn,omitempty"`
	LastEventOriginGeolocationAso         string  `json:"last_event_origin_geolocationAso,omitempty"`
	LastEventOriginGeolocationCountryCode string  `json:"last_event_origin_geolocationcCuntryCode,omitempty"`
	LastEventOriginGeolocationAccuracy    int32   `json:"last_event_origin_geolocationaAcuracy,omitempty"`

	LastEventTargetBytesSent        float64 `json:"last_event_target_bytesSent,omitempty"`
	LastEventTargetBytesReceived    float64 `json:"last_event_target_bytesReceived,omitempty"`
	LastEventTargetPackagesSent     int64   `json:"last_event_target_packagesSent,omitempty"`
	LastEventTargetPackagesReceived int64   `json:"last_event_target_packagesReceived,omitempty"`
	LastEventTargetConnections      int64   `json:"last_event_target_connections,omitempty"`
	LastEventTargetUsedCpuPercent   int64   `json:"last_event_target_usedCpuPercent,omitempty"`
	LastEventTargetUsedMemPercent   int64   `json:"last_event_target_usedMemPercent,omitempty"`
	LastEventTargetTotalCpuUnits    int64   `json:"last_event_target_totalCpuUnits,omitempty"`
	LastEventTargetTotalMem         int64   `json:"last_event_target_totalMem,omitempty"`
	LastEventTargetIp               string  `json:"last_event_target_ip,omitempty"`
	LastEventTargetHost             string  `json:"last_event_target_host,omitempty"`
	LastEventTargetUser             string  `json:"last_event_target_user,omitempty"`
	LastEventTargetGroup            string  `json:"last_event_target_group,omitempty"`
	LastEventTargetPort             int64   `json:"last_event_target_port,omitempty"`
	LastEventTargetDomain           string  `json:"last_event_target_domain,omitempty"`
	LastEventTargetFqdn             string  `json:"last_event_target_fqdn,omitempty"`
	LastEventTargetMac              string  `json:"last_event_target_mac,omitempty"`
	LastEventTargetProcess          string  `json:"last_event_target_process,omitempty"`
	LastEventTargetFile             string  `json:"last_event_target_file,omitempty"`
	LastEventTargetPath             string  `json:"last_event_target_path,omitempty"`
	LastEventTargetHash             string  `json:"last_event_target_hash,omitempty"`
	LastEventTargetUrl              string  `json:"last_event_target_url,omitempty"`
	LastEventTargetEmail            string  `json:"last_event_target_email,omitempty"`

	LastEventTargetGeolocationCountry     string  `json:"last_event_target_geolocationCountry,omitempty"`
	LastEventTargetGeolocationCity        string  `json:"last_event_target_geolocationCity,omitempty"`
	LastEventTargetGeolocationLatitude    float64 `json:"last_event_target_geolocationLatitude,omitempty"`
	LastEventTargetGeolocationLongitude   float64 `json:"last_event_target_geolocationLongitude,omitempty"`
	LastEventTargetGeolocationAsn         int64   `json:"last_event_target_geolocationAsn,omitempty"`
	LastEventTargetGeolocationAso         string  `json:"last_event_target_geolocationAso,omitempty"`
	LastEventTargetGeolocationCountryCode string  `json:"last_event_target_geolocationcCuntryCode,omitempty"`
	LastEventTargetGeolocationAccuracy    int32   `json:"last_event_target_geolocationaAcuracy,omitempty"`

	GPTTimestamp      string `json:"gpt_timestamp,omitempty"`
	GPTClassification string `json:"gpt_classification,omitempty"`
	GPTReasoning      string `json:"gpt_reasoning,omitempty"`
	GPTNextSteps      string `json:"gpt_next_steps,omitempty"`
}
